### ISSUE TITLE
新版毕业论文规范更新

### ISSUE THREAD

**Issue by MayeZhang** [hithesis/hithesis#123]
**描述bug类型**

- 校区（哈尔滨/威海/深圳？）：哈尔滨

- 学位（本/硕/博？）：硕

- 论文类型（毕业论文/开题/中期/博后/English Version？）：毕业论文

- 证据（与规范不符/与word模板不符？）：与规范不符

- 证据所在网页（窝工规范或者word模板所在窝工官方网页）：http://hitgs.hit.edu.cn/2216/list.htm

**描述bug具体信息** 

如图：**左侧为新版的规范**

![5693534517E20E1A709F0CE17B5BC6F4](https://user-images.githubusercontent.com/42532687/166609735-00dfdc85-2213-40a2-8a60-1f13d0c496cf.jpg)

![1F31061500E7B7E7314D9941C8C9A036](https://user-images.githubusercontent.com/42532687/166609787-c3682de0-4f31-4e0a-98db-7e83e4ff8a48.jpg)

![406A148C6CCB868F7B8EA294107AF361](https://user-images.githubusercontent.com/42532687/166609799-5dc4713b-4913-449d-ae1a-edd70a89beca.jpg)

**Comment by jklm23** [comment]
个人修改方法：
1. `hithesisbook.cfg`的`158`行：`\gdef\hit@cdegree{\hit@cxueke\hit@cxuewei}`改为`\gdef\hit@cdegree{\hit@cxuewei}`

**Comment by MayeZhang** [comment]
> 个人修改方法：
> 
> 1. `hithesisbook.cfg`的`158`行：`\gdef\hit@cdegree{\hit@cxueke\hit@cxuewei}`改为`\gdef\hit@cdegree{\hit@cxuewei}`

你这样内封里申请学位那个就变成了：硕士
我是直接在cls文件里面修改的，另外英文的那个内封也要变一下

**Comment by MayeZhang** [comment]
> 个人修改方法：
> 
> 1. ~`hithesisbook.cfg`的`158`行：`\gdef\hit@cdegree{\hit@cxueke\hit@cxuewei}`改为`\gdef\hit@cdegree{\hit@cxuewei}`~ 在`hithesisbook.cfg`搜索`\ifhit@master`的那一项，添加`\gdef\hit@[name]{\hit@cxuewei}`，`[name]`可以随便起一个；
> 2. `hithesisbook.cls`的`391`行`\fancyhead[C]{\songti\xiaowu[0]\hit@cschoolname\hit@cdegree\hit@cthesisname}`改为`\fancyhead[C]{\songti\xiaowu[0]\hit@cschoolname\hit@[name]\hit@cthesisname}`，`[name]`与上面的一致
> 
> 应该是这样，不知道有没有更简单的方法

其实不用新起一个，你这里直接把@cdegree改成@cxuewei就可以了，还有几个地方也是类似

**Comment by syvshc** [comment]
我在链接 http://hitgs.hit.edu.cn/2216/list.htm 中下载的 [研究生学位论文书写范例（理工类）](http://hitgs.hit.edu.cn/2021/0513/c3368a254243/page.htm) 中的学科部分显示是

![image](https://user-images.githubusercontent.com/38098591/170673788-ce10b1c3-c9d7-4158-b6cd-4fa9e92735fb.png)

并不是学科或类别，请问有相关的说明吗？

**Comment by MayeZhang** [comment]
> * http://hitgs.hit.edu.cn/2216/list.htm

研究生学位论文写作指南（理工类）第11页
http://hitgs.hit.edu.cn/2021/0429/c3425a253487/page.htm

**Comment by syvshc** [comment]
啧……那我可以把 issue 题目中的那个书写范例看成是博士的，这个指南看成硕士的？

这书写指南和书写范例冲突了哇.。

**Comment by syvshc** [comment]
另外在书写指南中的申请学位处 
![image](https://user-images.githubusercontent.com/38098591/170806899-7b06ce97-60cb-4407-b84c-5ff989350832.png)
后面的三个空是要瑱什么呢……

**Comment by MayeZhang** [comment]
> 啧……那我可以把 issue 题目中的那个书写范例看成是博士的，这个指南看成硕士的？
> 
> 这书写指南和书写范例冲突了哇.。

这个地方确实是冲突了，指南里是写到了硕士和博士的。这个感觉还是先按学科走？

**Comment by syvshc** [comment]
> 这个地方确实是冲突了，指南里是写到了硕士和博士的。这个感觉还是先按学科走？

先按学科走吧，然后我提供一个手动修改的方法。或者提供一个选项？

**Comment by MayeZhang** [comment]
![image](https://user-images.githubusercontent.com/42532687/170807059-12a9cb80-e320-4850-85e3-7b5a1dd8173a.png)
我的是这样的，你下载的怎么多出来几个空啊？

**Comment by syvshc** [comment]
我开启了文档标记

![image](https://user-images.githubusercontent.com/38098591/170807156-07f393d2-108b-43b0-8a7e-74a8d5c765b6.png)

我我把空格显示关了之后发现那些框没了，那问题就是**学科或类别**和**UDC**的区别了。

**Comment by syvshc** [comment]
我知道了，我的那些方框是全角空格的标记。目前在 [dev](https://github.com/dustincys/hithesis/tree/dev) 已经将修改完成，可以自行测试。如果没有问题可以回复，我会在推送到 [master](https://github.com/dustincys/hithesis/tree/master) 分支之后关闭该 issue。

**Comment by MayeZhang** [comment]
关于研究生院的回复：
![image](https://user-images.githubusercontent.com/42532687/172091087-f6a5bf38-6468-40b4-af13-649d171ebde5.png)
**「附件」**：
![83327F7C84DDEF37D5D644B10F0C2E7D](https://user-images.githubusercontent.com/42532687/172091099-7d26ec2e-cf89-4ca2-92f5-d5f29165f10f.jpg)
![5C2C518C99975CF08D75170FF5718385](https://user-images.githubusercontent.com/42532687/172091102-b71c978d-053f-4e07-9ee6-8b46f4906f77.jpg)

**「回复」**：
![image](https://user-images.githubusercontent.com/42532687/172091201-fe0d67fb-cac4-40e1-a7c0-0324fb338515.png)
