### ISSUE TITLE
标题与编号间的空格与模板不一致

### ISSUE THREAD

**Issue by shen-wenxin** [hithesis/hithesis#129]
## 基本信息

- 校区（哈尔滨/威海/深圳？）：深圳

- 学位（本/硕/博？）：本

- 论文类型（毕业论文/开题/中期/博后/English Version？）：毕业论文

- 证据（与规范不符/与word模板不符？）：
![image](https://user-images.githubusercontent.com/65153863/169315136-8fcadf9e-d8c9-4051-b57c-578865d62e43.png)

- 证据所在网页（窝工规范或者word模板所在窝工官方网页）：http://due.hitsz.edu.cn/system/_content/download.jsp?urltype=news.DownloadAttachUrl&owner=1481660265&wbfileid=7782026

- LaTeX 发行版（TeXLive 20xx/MikTeX/**本模板不支持CTeX套装**）：TexLive 2022

- 模板版本（在 `hithesis***.cls` 中的 `\ProvidesClass` 命令中的 `3.x.xx` 即为版本号）：v3.1a

## 描述模板不符合的具体信息

窝工在（规范/word模板中）第（xxx）行规定格式为：需要空两个半角字符

如图：

hithesis的格式为

如图：
<img width="811" alt="f10b0d9c900af2297675d2e43c5c002" src="https://user-images.githubusercontent.com/65153863/169320755-02c59cea-381f-4979-a8d2-033e123ce32d.png">

如码：

**Comment by syvshc** [comment]
在 `hithesisbook.cls` 中的以下部分

```latex
  \ctexset{%
    chapter={
      afterindent=true,
      pagestyle={hit@headings},
      beforeskip={28.34646bp},%一个空行 1.57481 × 18
      afterskip={28.74646bp},%0.8应该不计算间距 0.8 × 18 + 0.57481×18
      aftername=\enspace,
      format={\centering\hit@title@font\xiaoer[1.57481]\ifhit@chapterbold\ifhit@bachelor\bfseries\fi\fi},%\center 会影响之后全局
      nameformat=\relax,
      numberformat=\relax,
      titleformat=\hit@chapter@titleformat,
      fixskip=true, % 添加这一行去除默认间距
      %hang=true,
    },
    section={
      afterindent=true,
      beforeskip={\ifhit@glue 19.84252bp \@plus 2.834646bp \@minus 0bp \else 19.84252bp \fi},%上下空0.5行
      afterskip={\ifhit@glue 19.84252bp \@plus 2.834646bp \@minus 0bp \else 19.84252bp \fi},
      format={\hit@title@font\ifhit@glue\fontsize{15bp}{21bp \@plus 1.677267bp \@minus 1.157391bp}\else\fontsize{15bp}{21bp}\fi\selectfont},
      aftername=\enspace,
      fixskip=true,
      break={},
    },
    subsection={
      afterindent=true,
      beforeskip={\ifhit@glue 17.00787bp \@plus 2.834646bp \@minus 0bp \else 17.00787bp \fi},
      afterskip={\ifhit@glue 17.00787bp \@plus 2.834646bp \@minus 0bp \else 17.00787bp \fi},
      format={\hit@title@font\ifhit@glue\fontsize{14bp}{18bp \@plus 1.842609bp \@minus 0.9920497bp}\else\fontsize{14bp}{18bp}\fi\selectfont},
      aftername=\enspace,
      fixskip=true,
      break={},
    },
    subsubsection={
      afterindent=true,
      beforeskip={\ifhit@glue 8.503937bp \@plus 2.834646bp \@minus 0bp \else 8.503937bp \fi},
      afterskip={\ifhit@glue 8.503937bp \@plus 2.834646bp \@minus 0bp \else 8.503937bp \fi},
      format={\hit@title@font\normalsize},
      aftername=\enspace,
      fixskip=true,
      break={},
    },
    paragraph/afterindent=true,
    subparagraph/afterindent=true
  }
```

中的 `aftername=\enspace` 全部替换为 `aftername=\quad`, 绪论部分的标题可以使用

```latex
\chapter{绪\quad 论}
```

来获得“绪论”中的两个半角空格. 

请暂时不要关闭这个 issue, 在我对格式进行更改完成并提交后, 我会关闭 issue.

**Comment by shen-wenxin** [comment]
<img width="641" alt="1652977340(1)" src="https://user-images.githubusercontent.com/65153863/169349854-cacb8d26-5ecd-4618-b37f-3b110f3aa0df.png">
您好，如果按照上述操作，参考文献序号之后也会变为两个半角空格，请问该如何解决呢

**Comment by shen-wenxin** [comment]
好的，辛苦您，谢谢

**Comment by syvshc** [comment]
在 `hithesisbook.cls` 中找到 `\@biblabel` 将对应的行进行替换

```
\ifhit@shenzhen
% TODO 添加 \mbox{} 防止标点挤压
  \def\@biblabel#1{\mbox{}［#1］}
\else
\fi
\renewenvironment{thebibliography}[1]{%
  \ifhit@openright\cleardoublepage\else\clearpage\fi\phantomsection%
  \hit@appendix@chapter*{\bibname}[\hit@bibname@etitle]
  \normalsize
  \list{\@biblabel{\@arabic\c@enumiv}}%
  {\renewcommand{\makelabel}[1]{##1}
  % TODO 深圳校区 bibwidth 和 labelsep
    \settowidth{\labelwidth}{\@biblabel{#1}}
    \setlength{\labelsep}{0pt}
    \setlength{\itemindent}{0pt}
    \setlength{\leftmargin}{\labelwidth}
```

**Comment by syvshc** [comment]
哦对了, 需要注意一下是不是需要用 `hitszthesis.bst`.

**Comment by shen-wenxin** [comment]
实在抱歉，想请问一下这个该在哪里确认是否使用呢

**Comment by syvshc** [comment]
你可以使用 `hitszthesis.bst` 与 `hithesis.bst` 分别生成一下参考文献来和目标样式比对一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月20日(周五) 凌晨2:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dustincys/hithesis] 标题与编号间的空格与模板不一致 (Issue #129)




 
实在抱歉，想请问一下这个该在哪里确认是否使用呢

**Comment by shen-wenxin** [comment]
您好，我修改了hithesisbook.cls之后问题已经解决，根据您的建议，我替换了替换了hitszthesis.bst，暂时没有其他格式问题，感谢您的解答。

**Comment by syvshc** [comment]
你的需求在 dev 分支中已经解决。https://github.com/dustincys/hithesis/commit/a85207a5453c9e2f6c4a58ac80f07fdbffd5794e
