### ISSUE TITLE
附录

### ISSUE THREAD

**Issue by Kingw413** [hithesis/hithesis#131]
## 基本信息

- 校区（哈尔滨）：

- 学位（本）：

- 论文类型（毕业论文）：

- LaTeX 发行版（TeXLive 2021）：

- 模板版本（3.0.20）：

## 想实现的效果
文献翻译和原文部分显示为附录I、附录II，且中文翻译部分在目录里显示节标题，即I.1,I.2,I.3等

**Comment by syvshc** [comment]
你想要的目录是

附录I 文献翻译
  I.1 第一节
  I.2 第二节
附录II 文献原文
而附录 II 中不显示节标题？

**Comment by Kingw413** [comment]
嗯嗯，不过附录II放的是原文图片，所以本来就没有节；应该只需要把原来的附录1改为附录I，附录2改成附录II就可以了

**Comment by syvshc** [comment]
```latex
\documentclass[type=bachelor,campus=harbin]{hithesisbook}
\begin{document}
  \tableofcontents
  \chapter{正文}
  \section{正文节}
  \begin{appendix}
    \ctexset{appendix/number=\Roman{chapter}}
    \renewcommand{\thesection}{\Roman{chapter}.\arabic{section}}
    \chapter{文献翻译}
    \section{翻译第一节}
    \section{翻译第二节}
    \chapter{文献原文}
    \includegraphics[width=\textwidth]{example-image}
  \end{appendix}
\end{document}
```

![image](https://user-images.githubusercontent.com/38098591/172062391-da6d1460-c8d4-4d05-addc-aad6059d0fcd.png)

**Comment by Kingw413** [comment]
！就是这样

**Comment by Kingw413** [comment]
感谢大佬

**Comment by Kingw413** [comment]
![image](https://user-images.githubusercontent.com/68884677/172063037-13d36023-1a27-4127-9da4-257f88e8c929.png)
大佬，插入英文文献原文时，页面格式和正文不一样了，这个可以改么
用的是\includepdf[pages=2-8]{1.pdf}命令

**Comment by syvshc** [comment]
`\includepdf`命令是插入pdf文件的命令, 你原来的pdf长什么样, 插进去就什么样.

**Comment by Kingw413** [comment]
ok，那我还是每页全转成图片再插入吧
