### ISSUE TITLE
latex中英文封面化学式区分大小写

### ISSUE THREAD

**Issue by hzjjzh** [hithesis/hithesis#133]
## 基本信息

- 校区（哈尔滨/威海/深圳？）：哈尔滨

- 学位（本/硕/博？）：硕

- 论文类型（毕业论文/开题/中期/博后/English Version？）：毕业论文

- LaTeX 发行版（TeXLive 20xx/MikTeX/**本模板不支持CTeX套装**）：Texlive 2022

- 模板版本（在 `hithesis***.cls` 中的 `\ProvidesClass` 命令中的 `3.x.xx` 即为版本号）： 3.0.2

## 想实现的效果

封面中英文题目化学式区分大小写

**Comment by syvshc** [comment]
可以考虑新定义命令, 在

```tex
\input{front/cover} % 封面
```

之前将需要正常大小写的化学式定义成命令, 比如

```tex
...
\DeclareRobustCommand{\mycea}{\ce{Cl2}}
\DeclareRobustCommand{\myceb}{\ce{H2O}}
\input{front/cover}
```

然后在 `cover.tex` 中的 `ctitle` 和 `etitle`  中的化学式分别用 `\mycmda`, `\mycmdb` 之类的代替.
