### ISSUE TITLE
知网查重把参考文献和原创性声明都包含进去了

### ISSUE THREAD

**Issue by iseesaw** [hithesis/hithesis#134]
## 描述bug类型

- 校区（哈尔滨/威海/深圳？）：哈尔滨

- 学位（本/硕/博？）：硕

- 论文类型（毕业论文/开题/中期/博后/English Version？）：毕业论文

- LaTeX 发行版（TeXLive 20xx/MikTeX/**本模板不支持CTeX套装**）：MikTex

- 模板版本（在 `hithesis***.cls` 中的 `\ProvidesClass` 命令中的 `3.x.xx` 即为版本号）：3.0.15

## 描述bug具体信息

知网查重时，貌似没识别出来参考文献和原创性声明部分，把这两部分都算进去了。查重率奇高 :(

**Comment by syvshc** [comment]
当时在把论文提交给秘书的时候要求我们删掉致谢和参考文献, 可以问一下答辩秘书

**Comment by iseesaw** [comment]
哦哦，感谢学长回复！我们没说这个问题（捂脸。。同学 Word 版本查重自动略过了参考文献，Latex 写的倒是没注意。。
