### ISSUE TITLE
威海校区本科生毕业论文与word模版不符

### ISSUE THREAD

**Issue by skumato** [hithesis/hithesis#135]
## 基本信息

- 校区（哈尔滨/威海/深圳？）：
威海
- 学位（本/硕/博？）：
本科生
- 论文类型（毕业论文/开题/中期/博后/English Version？）：
毕业论文
- 证据（与规范不符/与word模板不符？）：
与word模版不符
- 证据所在网页（窝工规范或者word模板所在窝工官方网页）：
[word模版附件](http://today.hitwh.edu.cn/2022/0513/c1024a155737/page.htm)
- LaTeX 发行版（TeXLive 20xx/MikTeX/**本模板不支持CTeX套装**）：

- 模板版本（在 `hithesis***.cls` 中的 `\ProvidesClass` 命令中的 `3.x.xx` 即为版本号）：
2021/05/17 v3.1
## 描述模板不符合的具体信息

窝工在word模板中第对章节标题的规定格式为：
章标题        黑体小2号字，多倍行距值1.25，段前20磅，段后10磅；
节标题        黑体小3号字，多倍行距值1.25，段前0.5行，段后0.5行；
条标题        黑体4号字，多倍行距值1.25，段前0.5行，段后0.5行；
款、项标题    黑体小4号字，多倍行距值1.25，段前0行，段后0行；
正文          宋体小4号字，多倍行距值1.25，段前0行，段后0行。

hithesis的格式看上去明显不同

**Comment by syvshc** [comment]
![image](https://user-images.githubusercontent.com/38098591/173172290-22521ac8-9c87-455d-9394-556e3c1c3093.png)

左 word, 右 hithesis

据我观察好像没有那么不同？

**Comment by syvshc** [comment]
经提醒 不同处出现在章标题上, 范例中有 “空一行” 的要求:

![image](https://user-images.githubusercontent.com/38098591/173173361-e233456a-18e5-4c54-ae56-f308fe131cf6.png)

可以在 `\documentclass` 下面加上

```latex
\ctexset{%
chapter={
  beforeskip={49bp},
  afterskip={46bp},
  }
}
```

**Comment by skumato** [comment]
收到，感谢大佬，效果和word模版几乎一样！

**Comment by dustincys** [comment]
这个是不是word和规范不一致？
