### ISSUE TITLE
两个连续的参考文献没有使用逗号隔开

### ISSUE THREAD

**Issue by cloudbird7** [hithesis/hithesis#137]
## 基本信息

- 校区（哈尔滨/威海/深圳？）：哈尔滨

- 学位（本/硕/博？）：硕士

- 论文类型（毕业论文/开题/中期/博后/English Version？）：毕业论文

- LaTeX 发行版（TeXLive 20xx/MikTeX/**本模板不支持CTeX套装**）：TeXLive 2022

- 模板版本（在 `hithesis***.cls` 中的 `\ProvidesClass` 命令中的 `3.x.xx` 即为版本号）：3.1b

## 描述模板不符合的具体信息
连续引用两篇参考文献的正确格式应该为“形成了多种数学模型[1,2]”,但模板给出的结果是“形成了多种数学模型[1-2]”
可参考模板自带\examples\hitbook\chinese 1.2.6节：
![pic](https://user-images.githubusercontent.com/54848703/173998156-33cbc3ac-ac47-4961-a430-69f65eb11506.png)

**Comment by syvshc** [comment]
请给出应该使用逗号隔开的规范或书写范例, 在国标 GB/T 7714-2015 中给出的示例为相邻的两个序号使用了 `-` 连接:

![image](https://user-images.githubusercontent.com/38098591/174014055-b605181b-f2a2-4a83-8bc0-23ff4e492b3b.png)

**Comment by cloudbird7** [comment]
>

**Comment by cloudbird7** [comment]
> 请给出应该使用逗号隔开的规范或书写范例, 在国标 GB/T 7714-2015 中给出的示例为相邻的两个序号使用了 `-` 连接:
> 
> ![image](https://user-images.githubusercontent.com/38098591/174014055-b605181b-f2a2-4a83-8bc0-23ff4e492b3b.png)

在窝工的模板和规则中并没有给出相邻两个序号的引用标准。但是根据实践，几乎所有学院都要求两个相邻序号使用逗号隔开，三个及以上相邻序号使用连字符连接 。在模板讨论群（851792460）中已有多位同学提出了类似需求，所以仍然主张应该添加对此功能的支持的选项。 @syvshc

**Comment by syvshc** [comment]
已经在 dev 分支中更新 `citetwo` 选项，可以在更新模板后使用

```latex
\documentclass[type=master,campus=harbin,citetwo=comma]{hithesisbook}
```

来应用更改。

或者在 

```latex
\documentclass[type=master,campus=harbin]{hithesisbook}
``` 

后使用

```latex
\makeatletter
\patchcmd{\NAT@citexnum}{\def@NAT@last@yr{-\NAT@penalty}}
  {%
    \ifx\NAT@last@yr\relax
    \def@NAT@last@yr{\@citea}%
    \else
    \def@NAT@last@yr{-\NAT@penalty}%
    \fi
  }%
  {}%
  {\fail}%
\makeatother
```

来临时应用更改。

**Comment by syvshc** [comment]
如果测试成功请不要主动关闭 issue，在新版本推送到 master 分支后我会关闭该 issue。

**Comment by cloudbird7** [comment]
测试成功 掌门威武
