### ISSUE TITLE
如何实现开题报告添加封面后的空白页，用于打印

### ISSUE THREAD

**Issue by qlongstudio** [hithesis/hithesis#138]
## 基本信息

- 校区（哈尔滨）：

- 学位（博）：

- 论文类型（开题）：

- LaTeX 发行版（TeXLive 20xx/MikTeX/**本模板不支持CTeX套装**）：

- 模板版本（在 `hithesis***.cls` 中的 `\ProvidesClass` 命令中的 `3.x.xx` 即为版本号）：

## 想实现的效果

如题，我想在开题报告pdf的封面页后加一页空白页（保证无页码的空白），用于打印。实际上我看到了教学里面的制作 打印版  的说明，但是好像无效。

**Comment by syvshc** [comment]
从实现角度来讲可以单独打印封面，再打印后面的内容。

我已经增加了一个选项 `print`, 可以在 dev 分支更新模板后在文档类选项中使用 `print=true` ld 增加封面后的空白页.
