### ISSUE TITLE
博士开题报告（哈尔滨）默认的文献引用格式文件 不显示期刊名

### ISSUE THREAD

**Issue by qlongstudio** [hithesis/hithesis#139]
## 描述bug类型

- 校区（哈尔滨）：

- 学位（博？）：

- 论文类型（开题）：

- LaTeX 发行版（TeXLive 20xx/MikTeX/**本模板不支持CTeX套装**）：

- 模板版本（在 `hithesis***.cls` 中的 `\ProvidesClass` 命令中的 `3.x.xx` 即为版本号）：

## 描述bug具体信息

- 请给出完整的示例文件：

```latex
% 将 thesis.tex/report.tex 中的内容完整地放在这里

```

或将整个 `hitbook/chinese`, `reports` 或 `reportplus` 压缩后上传 `.zip` 文件

- 使用什么编译方式（`xelatex`/`latexmk`/`make thesis`）：
- 编译报错 or 编译结果与预期不符：

- 如果有编译报错，可以将报错信息截图粘贴到下面：

- 如果编译结果与预期不符：
  - 预期结果的截图

  - 编译后的效果截图

- 将编译后产生的 `.log` 文件上传到这里。

**Comment by syvshc** [comment]
请提供 `\bibliographystyle` 一行的内容, 以及要引用的 `bib` 中的内容, 指明是哪一条不显示期刊名.
