### ISSUE TITLE
生成的hithesisart.cls出现bug，好像是tableofcontent命令的问题？

### ISSUE THREAD

**Issue by Gaming722** [hithesis/hithesis#141]
## 描述bug类型

- 校区（哈尔滨/威海/深圳？）：深圳

- 学位（本/硕/博？）：硕

- 论文类型（毕业论文/开题/中期/博后/English Version？）：开题

- LaTeX 发行版（TeXLive 20xx/MikTeX/**本模板不支持CTeX套装**）：TeXLive 2020

- 模板版本（在 `hithesis***.cls` 中的 `\ProvidesClass` 命令中的 `3.x.xx` 即为版本号）：v3.1b

## 描述bug具体信息

- 请给出完整的示例文件：

```latex
% 将 thesis.tex/report.tex 中的内容完整地放在这里

% !Mode:: "TeX:UTF-8"
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%          ,
%      /\^/`\
%     | \/   |                CONGRATULATIONS!
%     | |    |             SPRING IS IN THE AIR!
%     \ \    /                                                _ _
%      '\\//'                                               _{ ' }_
%        ||                     hithesis v3                { `.!.` }
%        ||                                                ',_/Y\_,'
%        ||  ,                   dustincys                   {_,_}
%    |\  ||  |\          Email: yanshuoc@gmail.com             |
%    | | ||  | |            https://yanshuo.name             (\|  /)
%    | | || / /                                               \| //
%    \ \||/ /       https://github.com/dustincys/hithesis      |//
%      `\\//`   \\   \./    \\ /     //    \\./   \\   //   \\ |/ /
%     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\documentclass[fontset=fandol,toc=true,type=master,stage=opening,campus=shenzhen]{hithesisart}
% 此处选项中不要有空格
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 必填选项
% type=doctor|master|bachelor
% stage=opening|midterm
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 选填选项（选填选项的缺省值已经尽可能满足了大多数需求，除非明确知道自己有什么
% 需求）
% campus=shenzhen|weihai|harbin
%   含义：校区选项，默认harbin
% fontset=windows|mac|ubuntu|fandol
%   含义：前三个对应各自系统，fandol是开源字体。
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


\graphicspath{{figures/}}


\begin{document}

\input{front/coverart.tex}
\makecover                          % !!!!!!!! \makecover这里报错，报错信息：Extra \else
                                 % 根据信息找到hithesisart.cls中的tableofcontent命令好像有问题。

% 深圳博士开题报告 -----------------------------------------------

\input{body/report_shenzhen_doctor_opening}

% 威海校区本科生开题报告结构 ----------------------------------------
% \input{body/report_weihai_bachelor_opening}
% \makebackcover
% -------------------------------------------------------------

% 威海校区本科生中期报告结构 ----------------------------------------
% \input{body/report_weihai_bachelor_midterm}
% \makebackcover
% -------------------------------------------------------------

% 哈尔滨校区本科生开题报告结构 --------------------------------------
% \input{body/report_harbin_bachelor_opening}
% -------------------------------------------------------------

\end{document}

% Local Variables:
% TeX-engine: xetex
% End:

```

- 使用什么编译方式（`xelatex`/`latexmk`/`make thesis`）：应该是xelatex?用的是vscode中的LaTeX Workshop插件
![image](https://user-images.githubusercontent.com/55038448/178268135-ad58658c-8e6b-4006-b455-2d7141ba3c14.png)

- 编译报错：\makecover报错，提示Extra \else

- 如果有编译报错，可以将报错信息截图粘贴到下面：
![image](https://user-images.githubusercontent.com/55038448/178268211-8306951d-9b94-4bbe-959b-753dd36aa6bd.png)

### 以下是tableofcontent命令的截图
![image](https://user-images.githubusercontent.com/55038448/178268372-24eb6d79-6ee5-43ab-a48a-0ad81f6bbcdc.png)

首先，感谢作者辛苦建立的hithesis模板。
本身对LaTex没有深入的了解，这里`\else\else\else\fi\fi\fi`是否有问题？
另外，虽然报错，但是pdf文件是有生成的，不过pdf文件中每一章的标题及参考文献没有居中显示；参考文献没有重起一页，紧跟着之前的文字；与[HITsz硕士学位论文开题报告模板](http://due.hitsz.edu.cn/info/1210/1827.htm)不符。

**Comment by syvshc** [comment]
收到反馈，issue 中提及的模板与 hithesis 有一些不符，需要时间来修改一下，包括目录，页眉等。

**Comment by Gaming722** [comment]
请问这里的`\else\else\else\fi\fi\fi`是否有问题？如果有，应该怎样修改？

**Comment by syvshc** [comment]
把三个 `\else` 删去，这里我改了一下实现，修改完成会推送到 dev 分支。

**Comment by syvshc** [comment]
我在 dev 分支更新了修改，您可以测试一下还有哪里有问题。

**Comment by Gaming722** [comment]
您好，首先感谢您的反馈如此迅速！
刚才测试了下还与[HITsz硕士学位论文开题报告模板](http://due.hitsz.edu.cn/info/1210/1827.htm)存在如下差异：

### 1. "参考文献"在目录以及正文中应不带序号：
- **word模板**:
![image](https://user-images.githubusercontent.com/55038448/178439999-09e84f35-c270-4fee-a24d-8d5d3665d965.png)
![image](https://user-images.githubusercontent.com/55038448/178439659-d83a989e-eaf7-4885-921f-724a9fda128d.png)



- **hithesis模板**:
![image](https://user-images.githubusercontent.com/55038448/178441054-93cffc7e-41d5-4171-bbd6-36774192c212.png)
![image](https://user-images.githubusercontent.com/55038448/178441148-f6506d52-9941-492a-9323-9f4b2d5594ba.png)


### 2. 目录中的小节标题与序号间应无空白：
- **word模板**:
![image](https://user-images.githubusercontent.com/55038448/178440556-3a8b1972-42dd-44c7-8886-fa5241d629e8.png)

- **hithesis模板**:
![image](https://user-images.githubusercontent.com/55038448/178441327-b3462e41-f58b-452a-b6ae-cd55676afb81.png)

### 3. 封面的字体字号存在差异： 不过不确定是否是我编译的问题，编译后有警告信息：
```
Font "FandolHei-Regular" does not contain requested
(fontspec)	Script "CJK".
```

- **word模板**:
![image](https://user-images.githubusercontent.com/55038448/178441846-f00cc5ac-39b8-4c34-ba28-f037cf33a795.png)

- **hithesis模板**:
![image](https://user-images.githubusercontent.com/55038448/178442114-89d471df-be93-4c2a-a32c-4c9815814e7c.png)

#### 4. 编译存在`Underfull \hbox (badness 10000)`警告，定位在report.tex中的\makecover命令，不过不影响封面生成。

**Comment by syvshc** [comment]
每次改深圳的模板都要骂骂咧咧的……我再改一下, 问题中提到的两个警告都不需要处理

**Comment by syvshc** [comment]
其中参考文献的部分可以使用
```latex
\section*{参考文献}
\addcontentsline{toc}{section}{参考文献}
\bibliographystyle{hithesis}
\bibliography{reference}
```

**Comment by syvshc** [comment]
根据 https://github.com/CTeX-org/forum/issues/194 修改的得到的没有间距的版本看起来与word也不一样

![image](https://user-images.githubusercontent.com/38098591/178460765-52664055-8a97-45f4-82ed-80b8d002b8c4.png)

我觉得还是应该给一点点间距

**Comment by syvshc** [comment]
可以在测试一下，其中参考文献部分不需要手动 `\section` 与 `\addcontentsline` 了

**Comment by Gaming722** [comment]
最新的dev分支已测试过无问题，可以说是东半球最接近[HITsz硕士学位论文开题报告模板](http://due.hitsz.edu.cn/info/1210/1827.htm)的模板了 :）
```latex
\clearpage %还需要加上这条命令
\bibliographystyle{hithesis}
\bibliography{reference}
```

**Comment by syvshc** [comment]
> \clearpage %还需要加上这条命令

不应该啊，我这里测试是不需要的

**Comment by Gaming722** [comment]
我的问题。。。
```latex
\subsection{解决方案}
123 %刚才这里没填内容，填上内容就好了，不需要加\clearpage
\bibliographystyle{hithesis}
\bibliography{reference}
```

**Comment by syvshc** [comment]
那我把这个 issue 标记为 fixed in dev 了，等到推送到 master 的时候我会关闭 issue。

**Comment by Gaming722** [comment]
好的，感谢维护。

**Comment by Gaming722** [comment]
添加一些使用过程中遇到的问题及找到的解决方案：

1. 未设置首行缩进2字符：
- 解决方案:
``` latex
% 首行缩进2字符
\usepackage{indentfirst}
\setlength{\parindent}{2em}
```

2. 未设置公式编号样式（ 规定中要求样式(1-1) ）：
- 解决方案：
``` latex
%公式、图、表编号
\makeatletter
\@addtoreset{equation}{section}
\makeatother
\renewcommand{\theequation}{\arabic{section}-\arabic{equation}}

\makeatletter
\@addtoreset{figure}{section}
\makeatother
\renewcommand{\thefigure}{\arabic{section}-\arabic{figure}}

\makeatletter
\@addtoreset{figure}{section}
\makeatother
\renewcommand{\thefigure}{\arabic{section}-\arabic{figure}}

\makeatletter
\@addtoreset{table}{section}
\makeatother
\renewcommand{\thetable}{\arabic{section}-\arabic{table}}
```

3. windows系统下`fontset=fandol`遇到偏僻字出现乱码：
- 解决方案：
``` latex
% fontset 还是选为windows
\documentclass[fontset=windows,toc=true,type=master,stage=opening,campus=shenzhen]{hithesisart} 
```

**Comment by syvshc** [comment]
1. 我这里测试没有遇到首行缩进的问题
2. Word 模板中没有关于公式图表编号的问题，模板里就不做调整了。
3. `fontset=fandol` 是作为全平台适配而使用的选项, 建议在搁平台选择自己的字体设置.
