### ISSUE TITLE
哈尔滨，博士中期目录、参考文献问题

### ISSUE THREAD

**Issue by nffxgln** [hithesis/hithesis#142]
## 基本信息

- 校区（哈尔滨/威海/深圳？）：哈尔滨

- 学位（本/硕/博？）：博

- 论文类型（毕业论文/开题/中期/博后/English Version？）：中期

- 证据（与规范不符/与word模板不符？）：中期没有规范

- 证据所在网页（窝工规范或者word模板所在窝工官方网页）：

- LaTeX 发行版（TeXLive 20xx/MikTeX/**本模板不支持CTeX套装**）：TeXLive 2020

- 模板版本（在 `hithesis***.cls` 中的 `\ProvidesClass` 命令中的 `3.x.xx` 即为版本号）：hithesis-v3.1c-dev

## 描述模板不符合的具体信息

窝工在（规范/word模板中）第（xxx）行规定格式为：

1. 目录无标题,怎么能加上目录标题？
2.  封面的研究生院制是否应改成'哈尔滨工业大学  和日期 '吗？
3. 参考文献去掉了section标号，目录就关联生成不了。

如图：![目录](https://user-images.githubusercontent.com/52684755/180630517-8bac4413-7ba9-42c3-9258-d625e61c154a.png)

hithesis的格式为

如图：

如码：

**Comment by syvshc** [comment]
“目录”标题要什么样式的呢？

**Comment by syvshc** [comment]
另外“哈尔滨工业大学+日期”需要的格式，日期与“中期报告日期”是否相同？

**Comment by nffxgln** [comment]
没有中期规范啊，我看我师姐的是黑体小二


--- 回复的原邮件 ----

| 发件人 | ***@***.***> |
| 发送日期 | 2022年7月24日 16:06 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [hithesis/hithesis] 哈尔滨，博士中期目录、参考文献问题 (Issue #142) |

“目录”标题要什么样式的呢？

**Comment by syvshc** [comment]
> 没有中期规范啊，我看我师姐的是黑体小二
> […](#)
> --- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 发送日期 | 2022年7月24日 16:06 | | 收件人 | ***@***.***> | | 抄送人 | ***@***.***> , ***@***.***> | | 主题 | Re: [hithesis/hithesis] 哈尔滨，博士中期目录、参考文献问题 (Issue #142) | “目录”标题要什么样式的呢？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

我知道没有规范，但是我写实现方法我得知道你想要什么样的啊。
目录标题的要求是居中，居左？字体字号？是否加粗？之类的需求请明确一下

**Comment by nffxgln** [comment]
噢噢，明白了，目录就是黑体，小二，居中
第二个问题，封面哈尔滨工业大学下面的日期和中期日期一样就好，类似与下面这样。


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年7月24日 16:22 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [hithesis/hithesis] 哈尔滨，博士中期目录、参考文献问题 (Issue #142) |

没有中期规范啊，我看我师姐的是黑体小二
…
--- 回复的原邮件 ---- | 发件人 | @.> | | 发送日期 | 2022年7月24日 16:06 | | 收件人 | @.> | | 抄送人 | @.> , @.> | | 主题 | Re: [hithesis/hithesis] 哈尔滨，博士中期目录、参考文献问题 (Issue #142) | “目录”标题要什么样式的呢？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***>

我知道没有规范，但是我写实现方法我得知道你想要什么样的啊。
目录标题的要求是居中，居左？字体字号？是否加粗？之类的需求请明确一下

**Comment by syvshc** [comment]
在 `\documentclass` 下面加上

```latex
\makeatletter
\pretocmd{\tableofcontents}{
  \ctexset{
    section/format=\centering\heiti\xiaoer,
  }
  \section*{\contentsname}
}{}{}
\renewcommand{\hit@harbin@schoolbottommark}{%
  \begin{center}
    \songti\sanhao\textbf{\kaishu 哈尔滨工业大学\\\hit@cdate}
  \end{center}
}
\makeatother
```

用来改封面和目录

在 `\section*{主要参考文献}` 下面加上

```
\addcontentsline{toc}{section}{主要参考文献}
```

其中的“主要参考文献”可以改成自己需要的文字。
