### ISSUE TITLE
如何将目录中的“Abstract”改成字母全部大写，并且删掉多出的空行？

### ISSUE THREAD

**Issue by TianXu1991** [hithesis/hithesis#145]
## 基本信息

- 校区（哈尔滨/威海/深圳？）：哈尔滨

- 学位（本/硕/博？）：博

- 论文类型（毕业论文/开题/中期/博后/English Version？）：毕业论文

- LaTeX 发行版（TeXLive 20xx/MikTeX/**本模板不支持CTeX套装**）：TeXLive 2020

- 模板版本（在 `hithesis***.cls` 中的 `\ProvidesClass` 命令中的 `3.x.xx` 即为版本号）：3.0.14

## 想实现的效果
这是问题：
如何将目录中的“Abstract”改成字母全部大写，并且删掉多出的空行？
![图片](https://user-images.githubusercontent.com/35133540/187010798-611f76a1-9e9a-4d59-81a2-3f736960523d.png)
这是期望的效果：
![图片](https://user-images.githubusercontent.com/35133540/187010836-3d7da812-a428-4ae3-a703-c824b6718f23.png)

**Comment by syvshc** [comment]
仔细阅读 `thesis.tex` 下方的选项说明:

```tex
% tocblank=true|false
%   含义：目录中第一章之前，是否加一行空白。缺省值为true。
% absupper=true|false
%   含义：中文目录中的英文摘要在中文目录中的大小写样式歧义，在规范中要求首
%   字母大写，在work样例中是全大写。该选项控制是否全大写。默认否。
```

**Comment by TianXu1991** [comment]
谢谢建议！但是，当我去掉tocblank的注释之后，出现如下编译错误，该如何解决呢？
![图片](https://user-images.githubusercontent.com/35133540/187011856-760132a0-c086-4eac-ba87-102a40b3d6c4.png)

**Comment by syvshc** [comment]
不是注释, 这是文档类的选项. 使用

```tex
\documentclass[tocblank=false, absupper=true, ...]{hithesis}
```

**Comment by TianXu1991** [comment]
谢谢你的帮助！按照你的建议，问题已解决。
