### ISSUE TITLE
哈尔滨硕士开题图标冒号与目录标题格式

### ISSUE THREAD

**Issue by LimbCC** [hithesis/hithesis#146]
## 基本信息

- 校区（哈尔滨/威海/深圳？）：哈尔滨

- 学位（本/硕/博？）：硕

- 论文类型（毕业论文/开题/中期/博后/English Version？）：开题

- 证据（与规范不符/与word模板不符？）：无

- 证据所在网页（窝工规范或者word模板所在窝工官方网页）：

- LaTeX 发行版（TeXLive 20xx/MikTeX/**本模板不支持CTeX套装**）：MikTeX

- 模板版本（在 `hithesis***.cls` 中的 `\ProvidesClass` 命令中的 `3.x.xx` 即为版本号）：3.1b

## 描述模板不符合的具体信息

窝工在（规范/word模板中）第（xxx）行规定格式为：

如图：
![image](https://user-images.githubusercontent.com/74044807/187361395-4b409880-9022-49aa-9dbe-517bb9d04741.png)

hithesis的格式为

如图：
![image](https://user-images.githubusercontent.com/74044807/187361177-ce4ff1ce-48ca-442e-aecb-5e99fab6f6ff.png)
![image](https://user-images.githubusercontent.com/74044807/187361508-18b03619-4026-4d32-97d9-70fd36fd280b.png)

目录没有标题，章节后没有省略号，章节间间距有些宽，然后图表标号应该是没有冒号吧

**Comment by wangwangbu** [comment]
图表标题我的解决方案，提供参考
编号带章节号：在`.cfg`文件添加
```
\counterwithin{figure}{section}
\counterwithin{table}{section}
```
标题去冒号：在`cls`文件添加`\RequirePackage{caption}`并在`\begin{document}`下添加
```
\captionsetup[figure]{labelsep=space} 
\captionsetup[table]{labelsep=space}
```

等一个官方修正

**Comment by syvshc** [comment]
我看看这个目录格式……怎么感觉这么怪呢

**Comment by syvshc** [comment]
在 http://hitgs.hit.edu.cn/2015/1210/c3359a123058/page.htm 这里我没有找到目录相关的规范, 是规范更新了吗

**Comment by wangwangbu** [comment]
我是深圳的，参考的就是深圳规范http://due.hitsz.edu.cn/info/1211/1859.htm
