### ISSUE TITLE
模板采用的英文字体为Thames字体而非Times New Roman，尽管二者看上去很像。

### ISSUE THREAD

**Issue by ZhuZiliang** [hithesis/hithesis#148]
## 描述bug类型

- 校区（哈尔滨/威海/深圳？）：哈尔滨

- 学位（本/硕/博？）：硕

- 论文类型（毕业论文/开题/中期/博后/English Version？）：开题/中期

- LaTeX 发行版（TeXLive 20xx/MikTeX/**本模板不支持CTeX套装**）：overleaf在线编译

- 模板版本（在 `hithesis***.cls` 中的 `\ProvidesClass` 命令中的 `3.x.xx` 即为版本号）：v3.1c

## 描述bug具体信息

overleaf在线编译模板，字体选项选择fandol，得到的文件经过比对，发现采用的英文字体为Thames字体而非Times New Roman，尽管二者看上去很像。

**Comment by syvshc** [comment]
英文字体应该是 `TeX Gyre TermesX` 才对啊

**Comment by ZhuZiliang** [comment]
> 

我想表达的是pdf呈现的效果是Thames。在cls文件里我确实看见您说的这个TeX Gyre TermesX了，但是学校的要求是新罗马字体呀。

**Comment by syvshc** [comment]
我没懂您说的pdf呈现的效果是Thames是什么意思, 能否配合截图之类的说明一下？
