### ISSUE TITLE
非全日制教育的学生类型出现在全日制封面中

### ISSUE THREAD

**Issue by kilosens** [hithesis/hithesis#149]
## 描述bug类型

- 校区（哈尔滨/威海/深圳？）：哈尔滨

- 学位（本/硕/博？）：博

- 论文类型（毕业论文/开题/中期/博后/English Version？）：毕业论文

- LaTeX 发行版（TeXLive 20xx/MikTeX/**本模板不支持CTeX套装**）：TexLive 2021

- 模板版本（在 `hithesis***.cls` 中的 `\ProvidesClass` 命令中的 `3.x.xx` 即为版本号）：3.1b

## 描述bug具体信息

thesis.tex设置为：
\documentclass[fontset=fandol,type=doctor,campus=harbin]{hithesisbook}

编译完成后pdf封面为：

![hithesisbook-cls-cstudenttype-1](https://user-images.githubusercontent.com/29514457/194468823-02725a51-9785-4ccc-87c2-f624c9dfcdc5.PNG)

cover.tex中的  cstudenttype={学术学位论文}, %非全日制教育申请学位者  不应该在这里出现

## 问题定位及可能的修复：

将hithesisbook.cls文件的1264-1266行：
```
\begin{center}\xiaoer[1]\songti\bfseries
  \hit@cbraceleft\hit@cstudenttype\hit@cbraceright
\end{center}
```
修改为：

```
\ifhit@fulltime
  \begin{center}\xiaoer[1]\songti\textbf{}\end{center}
\else
  \begin{center}\xiaoer[1]\songti\textbf{\hit@cbraceleft\hit@cstudenttype\hit@cbraceright}\end{center}
\fi
```

修改后：

![hithesisbook-cls-cstudenttype-2](https://user-images.githubusercontent.com/29514457/194469130-de985dbb-0b1c-4892-8a88-18f2ba111961.PNG)

代码修改：

![hithesisbook-cls-cstudenttype-fix](https://user-images.githubusercontent.com/29514457/194469179-d4a0fe57-ab91-44e2-9a89-ff522285c667.PNG)

未完整测试，目前未发现其他异常

**Comment by kilosens** [comment]
#120

**Comment by syvshc** [comment]
您好, 我想确认一下, 非全是不需要

```
(学术学位论文)
```

这一行, 而全日制需要是吗

**Comment by kilosens** [comment]
> 您好, 我想确认一下, 非全是需要
> 
> ```
> (学术学位论文)
> ```
> 
> 这一行, 而全日制不需要是吗

全日制不需要，非全日制不清楚

**Comment by syvshc** [comment]
> 全日制不需要，非全日制不清楚

好的, 如果您在校的话能否帮忙查看一下书写范例文档? 我这里没有权限查看.

**Comment by kilosens** [comment]
> > 全日制不需要，非全日制不清楚
> 
> 好的, 如果您在校的话能否帮忙查看一下书写范例文档? 我这里没有权限查看.

抱歉，我也被搞懵了

[https://hitgs.hit.edu.cn/2021/0513/c3425a254242/page.htm](url)
研究生学位论文书写范例（理工类） 这个文件里封面是有（学术学位论文）的，并且没有区分是否全日制
[https://hitgs.hit.edu.cn/2021/0429/c3425a253487/page.htm](url)
研究生学位论文写作指南（理工类） 这个文件3.3节的说明封面是有（学术学位论文）的，且没有区分是否全日制，但文件最后给出的封面示例全日制没有（学术学位论文）
这两个文件都是2021年的

另外我看了19，20，21年的全日制博士毕业论文，没有（学术学位论文）

所以书写范例我也没法确定用哪个，我现在按全日制没有（学术学位论文）写了

**Comment by kilosens** [comment]
目前我只找到这个毕业论文格式参考，如果有别的参考来源我可以帮忙下载

**Comment by syvshc** [comment]
您可以使用 dev 分支的 `hithesis.dtx` 来生成新的 `hithesisbook.cls` 来检查一下修复是否正确

**Comment by kilosens** [comment]
> 您可以使用 dev 分支的 `hithesis.dtx` 来生成新的 `hithesisbook.cls` 来检查一下修复是否正确, 如果没有问题的话请不要关闭 issue, 我会在更新正式版的时候统一关闭.

用dev分支简单测试了一下没问题，感谢

**Comment by syvshc** [comment]
根据 #97 和 #155 来看深圳硕士还是需要这个 `cstudenttype` 的……真是令人头疼
