### ISSUE TITLE
哈工大深圳博士中期报告hithesis模版与规范不符

### ISSUE THREAD

**Issue by heany** [hithesis/hithesis#150]
## 基本信息

- 校区（哈尔滨/威海/深圳？）：深圳

- 学位（本/硕/博？）：博士

- 论文类型（毕业论文/开题/中期/博后/English Version？）：中期

- 证据（与规范不符/与word模板不符？）：哈工大深圳博士中期报告在2022年3月29号更新，变化不是很大，主要在模版的最后两页内容

- 证据所在网页（窝工规范或者word模板所在窝工官方网页）：http://due.hitsz.edu.cn/info/1253/4050.htm

- LaTeX 发行版（TeXLive 20xx/MikTeX/**本模板不支持CTeX套装**）：

- 模板版本（在 `hithesis***.cls` 中的 `\ProvidesClass` 命令中的 `3.x.xx` 即为版本号）：v3.1.b

## 描述模板不符合的具体信息

窝工在（规范/word模板中）【指导教师意见部分&检查小组意见部分】规定格式如下图所示：

如图：
<img width="564" alt="image" src="https://user-images.githubusercontent.com/28182428/195526042-b3cf1af6-8d35-4f7d-99dd-671ed3681d5d.png">

<img width="574" alt="image" src="https://user-images.githubusercontent.com/28182428/195526438-6391f2b4-a54f-413e-8874-33f6aea337fc.png">

hithesis的格式为

如图：
<img width="829" alt="image" src="https://user-images.githubusercontent.com/28182428/195526369-37d26db8-002d-4a98-af29-a93b15280f0c.png">

**Comment by syvshc** [comment]
深圳格式太乱了……这里也不好更改, 也不确定明后年深圳又要搞什么事情. 我建议用pdf编辑软件手动更改这些内容吧……
