### ISSUE TITLE
使用xelatex时候必须到这里必须回车一下 可能是遇到了什么问题？

### ISSUE THREAD

**Issue by BaileysRock** [hithesis/hithesis#151]
## 基本信息

- 校区（哈尔滨/威海/深圳？）：哈尔滨

- 学位（本/硕/博？）：本

- 论文类型（毕业论文/开题/中期/博后/English Version？）：开题

- LaTeX 发行版（TeXLive 20xx/MikTeX/**本模板不支持CTeX套装**）：texlive 2019

- 模板版本（在 `hithesis***.cls` 中的 `\ProvidesClass` 命令中的 `3.x.xx` 即为版本号）：

![image](https://user-images.githubusercontent.com/55704024/196004538-e70e7fca-a35a-4dbb-8d8e-3bb1b1119760.png)

**Comment by syvshc** [comment]
请问是什么操作系统呢？是 mac 吗

**Comment by BaileysRock** [comment]
> 

ubuntu 20.04

**Comment by syvshc** [comment]
emm 不过你的命令行显示你用的 texlive 2022 ?

**Comment by syvshc** [comment]
我这里测试了一下, 问题复现了, 稍后修复

**Comment by syvshc** [comment]
可以拉取一下 [dev](https://github.com/hithesis/hithesis/tree/dev) 分支的全部文件并重新生成 `.cfg` 文件, 并且注意会在 `example/hitart/reports` 文件下生成一个 `hrb-bachelor-bottommark.eps` 的图片文件, 编译时会用到.

**Comment by syvshc** [comment]
如果测试没有问题的话请回复一下, 并且不要主动关闭此 issue, 在 `v3.1c` 更新正式版以后会统一关闭.

**Comment by BaileysRock** [comment]
感谢解答~
问题已经解决了
