### ISSUE TITLE
硕士毕业论文封面的"硕士学位论文"和"专业学位论文"的字体粗细存在差异

### ISSUE THREAD

**Issue by jiangsadyodi** [hithesis/hithesis#152]
## 基本信息

- 校区（哈尔滨/威海/深圳？）：哈尔滨

- 学位（本/硕/博？）：硕

- 论文类型（毕业论文/开题/中期/博后/English Version？）：毕业论文

- 证据（与规范不符/与word模板不符？）：与word模板不符

- LaTeX 发行版（TeXLive 20xx/MikTeX/**本模板不支持CTeX套装**）：TeXLive 2022

- 模板版本（在 `hithesis***.cls` 中的 `\ProvidesClass` 命令中的 `3.x.xx` 即为版本号）：3.0.16

## 描述模板不符合的具体信息
硕士毕业论文封面的"硕士学位论文"和"专业学位论文"的**字体粗细**存在差异，hithesis生成的似乎比规范中**更粗**。
窝工在word模板封面页中有：
![image](https://user-images.githubusercontent.com/116239407/196841818-eb595271-ca8b-4ab0-8f7a-c4f7b957636a.png)
hithesis生成的pdf为
![image](https://user-images.githubusercontent.com/116239407/196842183-2bb6b684-8588-443a-824e-fa6f9b545363.png)

两者放大对比后会更加明显
![image](https://user-images.githubusercontent.com/116239407/196844706-bb4de79b-4902-4038-8b3a-126baea5fb11.png)

如码：
hithesisbook.cls
```
1207 %封面一
1214 \begin{center}\xiaoyi[1]\songti\textbf{\hit@cxuewei\hit@cthesisname}\end{center}
1215 \begin{center}\xiaoer[1]\songti\textbf{\hit@cbraceleft\hit@cstudenttype\hit@cbraceright}\end{center}
```

模板使用\textbf使得宋体加粗，但是应该如何调整加粗的**粗细度**呢？

## 尝试解决方法
[https://blog.csdn.net/qq_29068833/article/details/106135696](url)
参考上述网页得知[AutoFakeBold = {3.17}]命令能够调整粗细程度，但是经过尝试，不知道如何加入到cls中。

#141 中提到了3. 封面的字体字号存在差异： 不过不确定是否是我编译的问题，编译后有警告信息：
似乎也存在粗细不同的问题

**Comment by syvshc** [comment]
这个呢……与字体的选择有关, 如果你是windows系统的话, 选 `fontset=windows` 试试？

**Comment by jiangsadyodi** [comment]
确实是字体的选择问题。我是windows下用虚拟机安装的ubuntu18.04.
一开始使用的是fontset=fandol，改成fontset=ubuntu后合理了。
是我注释看的不仔细。つ﹏⊂。感谢~
