### ISSUE TITLE
深圳校区硕士毕业论文参考文献中的中文括号显示不出来

### ISSUE THREAD

**Issue by zicaijun** [hithesis/hithesis#154]
## 基本信息

- 校区（哈尔滨/威海/深圳？）：深圳

- 学位（本/硕/博？）：硕

- 论文类型（毕业论文/开题/中期/博后/English Version？）：毕业论文

- LaTeX 发行版（TeXLive 20xx/MikTeX/**本模板不支持CTeX套装**）：TeXLive 2022

- 模板版本（在 `hithesis***.cls` 中的 `\ProvidesClass` 命令中的 `3.x.xx` 即为版本号）：3.1b

## 想实现的效果
深圳校区硕士毕业论文的新格式，将参考文献中的括号改成中文括号，但是直接编译的时候还是英文括号。
下图是想要实现的效果
![image](https://user-images.githubusercontent.com/27126670/204000029-134e051d-5358-4ab2-a867-5a1eabd9a13b.png)

**Comment by syvshc** [comment]
请提供新规范的链接或文件

**Comment by zicaijun** [comment]
> 请提供新规范的链接或文件

您好，这个是新规范的文件样例
[1.2哈尔滨工业大学（深圳）全日制硕士研究生学位论文书写范例-理工类（2021版，修订处涂红）.zip](https://github.com/hithesis/hithesis/files/10093428/1.2.-.2021.zip)

**Comment by syvshc** [comment]
我看了一下代码, 这部分应该是在 057fcf6eb8368a0c59b3b95a29f97 处改动过了, 您看一下生成的文件中有没有一个 `hitszthesis.bst` 文件, 以及 `thesis.tex` 中是否有这一句
https://github.com/hithesis/hithesis/blob/d09788689089b99d15d1f95fe819d395305e60f6/examples/hitbook/chinese/thesis.tex#L114
如果有的话, 请使用 `hitszthesis` 样式, 并且注释掉其他的 `\bibliographystyle` 命令, 删除 `thesis.bbl` 文件重新使用 `make thesis` 进行完整编译
