### ISSUE TITLE
深圳校区格式变化，需要修改

### ISSUE THREAD

**Issue by ShixingHuang** [hithesis/hithesis#155]
## 基本信息

- 校区（哈尔滨/威海/深圳？）：深圳

- 学位（本/硕/博？）：硕

- 论文类型（毕业论文/开题/中期/博后/English Version？）：毕业论文

- 证据（与规范不符/与word模板不符？）：规范又改了，难受，还好改了页眉和封面，扉页。latex小白求助

- 证据所在网页（窝工规范或者word模板所在窝工官方网页）：

- LaTeX 发行版（TeXLive 20xx/MikTeX/**本模板不支持CTeX套装**）：

- 模板版本（在 `hithesis***.cls` 中的 `\ProvidesClass` 命令中的 `3.x.xx` 即为版本号）：

## 描述模板不符合的具体信息

窝工在（规范/word模板中）第（xxx）行规定格式为：

如图：
![image](https://user-images.githubusercontent.com/78217007/204221000-04f6c880-9708-42c1-84c6-58e9f2bb4219.png)
![image](https://user-images.githubusercontent.com/78217007/204221055-e293fe75-ca73-4123-b9cb-a7eb999c1e76.png)

hithesis的格式为

如图：
![image](https://user-images.githubusercontent.com/78217007/204221343-3d572e03-1122-4b44-a808-fc3ac753dc9e.png)
![image](https://user-images.githubusercontent.com/78217007/204221389-079a60ee-de40-4009-a261-f78d9804c70b.png)
![image](https://user-images.githubusercontent.com/78217007/204221440-3881a6b1-5c39-427b-a9b1-2813f0a3e900.png)

**Comment by syvshc** [comment]
看得出来是很着急了……深圳的格式真的是一年一换, 改得心力憔悴了. 等我考完试再改吧, 话说有规范的文件或者链接吗？

**Comment by syvshc** [comment]
在 dev 分支已经更新，请测试效果，如果效果正确请不要自行关闭此 issue，推送到 master 分支时我会关闭
