### ISSUE TITLE
英文目录中“附录”英文翻译为Chapter

### ISSUE THREAD

**Issue by qujiangLSW** [hithesis/hithesis#162]
学位论文模板中的英文目录，附录的翻译显示的是Chapter A，应该为Appendix才对，此外索引两个字中间无间距。

**Comment by syvshc** [comment]
提供一下模板的版本, 以及哪个校区的哪个阶段的模板？我这里用 3.1c 测试没有问题. 
![image](https://user-images.githubusercontent.com/38098591/226107964-cfaaa6a2-7cd5-4313-aea4-1087ac92161f.png)
另外我没找到索引的书写范例, 可以提供一下吗

**Comment by qujiangLSW** [comment]
你好，刚看了一下我的是应该还是0.0.1版本的。请问这个更换新版本的话，是否麻烦？不是很熟悉这个，谢谢








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hithesis/hithesis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月18日(星期六) 晚上9:06
***@***.***&gt;;
抄送:&nbsp;"曲江 断云 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [hithesis/hithesis] 英文目录中“附录”英文翻译为Chapter (Issue #162)





 
提供一下模板的版本, 以及哪个校区的哪个阶段的模板？我这里用 3.1c 测试没有问题.
 
 另外我没找到索引的书写范例, 可以提供一下吗

**Comment by qujiangLSW** [comment]
还有一个问题想问一下，我这个0.0.0版本要是升级到最新版本，是不是只需要将ins和dtx文件直接覆盖就行呢？谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hithesis/hithesis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月18日(星期六) 晚上9:06
***@***.***&gt;;
抄送:&nbsp;"曲江 断云 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [hithesis/hithesis] 英文目录中“附录”英文翻译为Chapter (Issue #162)





 
提供一下模板的版本, 以及哪个校区的哪个阶段的模板？我这里用 3.1c 测试没有问题.
 
 另外我没找到索引的书写范例, 可以提供一下吗

**Comment by syvshc** [comment]
0.0.0过于古老了……应该只需要把内容放到新的模板中应该就可以……吧

**Comment by qujiangLSW** [comment]
好的，谢谢你




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月18日(星期六) 晚上10:20
收件人: ***@***.***&gt;; 
抄送: "曲江 断云 ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hithesis/hithesis] 英文目录中“附录”英文翻译为Chapter (Issue #162)





 
0.0.0过于古老了……应该只需要把内容放到新的模板中应该就可以……吧

**Comment by note286** [comment]
> 还有一个问题想问一下，我这个0.0.0版本要是升级到最新版本，是不是只需要将ins和dtx文件直接覆盖就行呢？谢谢


请看[模板的编译方法](https://github.com/hithesis/hithesis#%E6%A8%A1%E6%9D%BF%E7%9A%84%E7%BC%96%E8%AF%91%E6%96%B9%E6%B3%95)。
