### ISSUE TITLE
博士论文内封（第二个封面）中，“博士”与“学位论文”之间多出一个空格

### ISSUE THREAD

**Issue by woqucc** [hithesis/hithesis#164]
## 描述bug类型

- 校区（哈尔滨/威海/深圳？）：哈尔滨

- 学位（本/硕/博？）：博

- 论文类型（毕业论文/开题/中期/博后/English Version？）：毕业论文

- LaTeX 发行版（TeXLive 20xx/MikTeX/**本模板不支持CTeX套装**）：MikTeX

- 模板版本（在 `hithesis***.cls` 中的 `\ProvidesClass` 命令中的 `3.x.xx` 即为版本号）：3.1b

## 描述bug具体信息

- 请给出完整的示例文件：
博士论文内封（第二个封面）中，“博士”与“学位论文”之间多出一个空格：
![bug](https://user-images.githubusercontent.com/13159546/230379964-36150545-f219-47ca-ae06-194d348017ad.png)

将exmpales/hitbook/hithesisbook.cls中第1316-1317行之间的换行删除，可以恢复正常：

![debug](https://user-images.githubusercontent.com/13159546/230380260-d773b09d-edcc-459a-95a7-8a5d8087b9f4.png)

发现一个小小bug，不知道其他人是否遇到，希望能够有所帮助。

非常感谢作者提供的模板！

**Comment by syvshc** [comment]
这个问题在 3.1c (dev 分支) 中已经修复, 谢谢您的反馈.
