### ISSUE TITLE
本部本科毕业论文的封面及内封格式变动

### ISSUE THREAD

**Issue by Edmund-Lai** [hithesis/hithesis#172]
## 基本信息

- 校区（哈尔滨/威海/深圳？）：哈尔滨

- 学位（本/硕/博？）：本

- 论文类型（毕业论文/开题/中期/博后/English Version？）：毕业论文

- 证据（与规范不符/与word模板不符？）：与规范和word模板不符

- 证据所在网页（窝工规范或者word模板所在窝工官方网页）：http://jwc.hit.edu.cn/2566/list.htm
该网页中的”书写规范（理工类）“和”写作指南（理工类）“均有提及

## 描述模板不符合的具体信息

哈工大本部本科毕业论文修改了封面及内封的整体格式

新封面：
<img width="370" alt="image" src="https://user-images.githubusercontent.com/78189107/235576505-3822f5d3-77a0-4e61-b4d2-00cb35de3452.png">

新内封：
<img width="386" alt="image" src="https://user-images.githubusercontent.com/78189107/235576565-6e609ae7-24ca-46e2-9810-5900b773b68d.png">

hithesis的格式为

封面：
<img width="440" alt="image" src="https://user-images.githubusercontent.com/78189107/235576767-78d52682-a274-46cf-be00-59ed8775b64b.png">

内封：
<img width="389" alt="image" src="https://user-images.githubusercontent.com/78189107/235576794-39150bd9-bd07-4e20-ac79-45f634cb4d31.png">

**Comment by syvshc** [comment]
我最近没有电脑, 大概需要下周二(5.9)处理一下, 也可能更晚……如果时间比较紧急的话可以考虑注释掉 `\makecover` 命令, 用Word制作完封面后再pdf合并一下（

**Comment by uldlwliny** [comment]
# 基本信息
- 校区（哈尔滨/威海/深圳？）：哈尔滨
- 学位（本/硕/博？）：本
- 论文类型（毕业论文/开题/中期/博后/English Version？）：毕业论文
- 证据（与规范不符/与word模板不符？）：与规范和word模板不符
- 证据所在网页（窝工规范或者word模板所在窝工官方网页）：http://jwc.hit.edu.cn/2566/list.htm
该网页中的”书写规范（理工类）“和”写作指南（理工类）“均有提及
# 描述模板不符合的基本信息
在上述问题上补充一些：
- 更新了原创性说明与授权页
![image](https://user-images.githubusercontent.com/109843917/235902204-7120340f-94b5-4a1a-ba00-ef04bd0aa439.png)
- 页眉距顶部距离改动（暂时断了用pdf合并内容的想法
![image](https://user-images.githubusercontent.com/109843917/235902496-4a0fa112-7fc6-4e5e-8c14-728daae1c2cb.png)
- 页眉的文字改成了“本科毕业论文（设计）”（不过很好改就是了，上图中是我自己修改的结果）

**Comment by uldlwliny** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Edmund-Lai** [comment]
摘要及目录部分的页脚的横线，也就是`-`符号，可以通过`thesis.tex`中的开关`bsfrontpagenumberline`控制，注释中提示的是默认打开，但是实际上还是需要手动打开，如果可以的话麻烦修改一下这里的注释~

**Comment by syvshc** [comment]
对提出的问题进行了修改, 可以在 [dev 分支](https://github.com/hithesis/hithesis/tree/dev) 中进行测试, 如果有问题可以继续回复此 issue, 如果没有问题, 请回复并且不要主动关闭 issue, 在合并进 master 分支后我会将其关闭.
