### ISSUE TITLE
本科毕业设计正文及原创性声明

### ISSUE THREAD

**Issue by uldlwliny** [hithesis/hithesis#173]
## 基本信息

- 校区（哈尔滨/威海/深圳？）：哈尔滨

- 学位（本/硕/博？）：本

- 论文类型（毕业论文/开题/中期/博后/English Version？）：毕业论文

- 证据（与规范不符/与word模板不符？）：与规范与word模板不符

- 证据所在网页（窝工规范或者word模板所在窝工官方网页）：http://jwc.hit.edu.cn/2566/list.htm 中的书写规范与范例

- LaTeX 发行版（TeXLive 20xx/MikTeX/**本模板不支持CTeX套装**）：Texlive 2022

- 模板版本（在 `hithesis***.cls` 中的 `\ProvidesClass` 命令中的 `3.x.xx` 或 `3.xx` 即为版本号）：3.1b

### 页眉小字

窝工在（规范/word模板中）页眉小字：“本科毕业论文（设计）”

如图：
![image](https://user-images.githubusercontent.com/109843917/235927441-3a0a1bc3-f317-4884-9a7a-4694f7e4d3e6.png)

hithesis的格式为：”本科毕业设计（论文）“

如码：`\def\hit@bachelor@cxuewei{本科} \def\hit@bachelor@cthesisname{毕业设计（论文）}`

### 页眉到页面顶端距离

如图（左为规范/word模板输出页面，右为hithesis输出页面，二者拼接于同一pdf文档中，SumatraPDF双页视图）：
![image](https://user-images.githubusercontent.com/109843917/235929428-2ac8e40a-c030-429e-b309-76e16c8246df.png)

### 原创性声明及授权

窝工在（规范/word模板中）规定的格式

如图：
![image](https://user-images.githubusercontent.com/109843917/235929702-96d52d5e-6831-44b8-b86d-1b3b47f56e28.png)

hithesis的格式

如图：
![image](https://user-images.githubusercontent.com/109843917/235929908-90801201-8360-43cd-82c3-37dd3e9a2595.png)

---

与[Issue#172中评论](https://github.com/hithesis/hithesis/issues/172#issuecomment-1532862433)提出的问题一致

**Comment by syvshc** [comment]
看了一眼新的规范, 这变的幅度还挺大啊……第一封面几乎全改了这是

**Comment by uldlwliny** [comment]
是这样的。正文的改动都是那些很细碎但很明显能分辨的地方，比如页边距、每行字数这种；而且书写范例非常经典地和书写规范多有出入😅。封面可以pdf剪切，正文及以后的比较棘手。辛苦您维护了🫡

**Comment by syvshc** [comment]
对提出的问题进行了修改, 可以在 [dev 分支](https://github.com/hithesis/hithesis/tree/dev) 中进行测试, 如果有问题可以继续回复此 issue, 如果没有问题, 请回复并且不要主动关闭 issue, 在合并进 master 分支后我会将其关闭.

**Comment by uldlwliny** [comment]
上述问题基本解决了，还有这样几个细节：
- 目录样式（左为dev编译，右为word模板）：“绪论”中间的空格和页码位置（页码位置应该是geometry设置的问题？和底下的几个地方应该是统一的）
![image](https://github.com/hithesis/hithesis/assets/109843917/47c58378-7f70-46c4-87f1-ed7294a64cd3)
- 正文顶端及底端边距设置（左为word模板，右为dev编译）：正文body的垂直高度似乎要小一圈
![image](https://github.com/hithesis/hithesis/assets/109843917/fa7a4a2c-96ee-4fce-99b9-46168ed474fa)
- 后文的顶端设置（左为word模板，右为dev编译）：word模板正文部分顶端间隔大，后文部分顶端间隔又同时变小（😅学校给的范例自己前后都不统一）
![image](https://github.com/hithesis/hithesis/assets/109843917/8410e671-2815-4bd8-972a-5f0f4129159c)
![image](https://github.com/hithesis/hithesis/assets/109843917/21507a3b-7334-42e8-b92a-b61f14de0baa)
---
其他的细节都能通过模板的开关实现复刻（比如tex输出字体的加粗）；目前没再发现其他问题

**Comment by syvshc** [comment]
> 绪论中间的空格

一会改一下

> 页码位置

页码的位置我没有调, 也可以调一下, 

> 正文顶端及底端边距设置

text 的大小就这么地吧, 老师估计也不能用标尺去对比, 

> 后文的顶端设置

这里我也处理一下吧, 我还特意给原创性声明套了个 `group` ...

**Comment by syvshc** [comment]
嗯……我发现绪论这个不是模板层面的东西, 直接使用 `\chapter{绪\qquad 论}` 即可, 间距可以自己对比调整

**Comment by syvshc** [comment]
发现了一个更大的问题, 正文和封面需要两种 `\geometry`... 真是要了亲命了

**Comment by syvshc** [comment]
再看一下 dev 分支吧, 又改了一版（瘫

**Comment by uldlwliny** [comment]
完事了，至少我没看出别的问题🤣辛苦啦🤝🏻

**Comment by syvshc** [comment]
> 完事了，至少我没看出别的问题🤣辛苦啦🤝🏻

ok, 您也辛苦了

**Comment by syvshc** [comment]
我发现可以用 milestone 来记录 issue, 那之前的方案可以抛弃了, 关闭此 issue 了.
