### ISSUE TITLE
深圳校区页眉问题

### ISSUE THREAD

**Issue by ltngiu** [hithesis/hithesis#177]
## 描述bug类型

- 校区（哈尔滨/威海/深圳？）：深圳

- 学位（本/硕/博？）：硕

- 论文类型（毕业论文/开题/中期/博后/English Version？）：开题&中期

- LaTeX 发行版（TeXLive 20xx/MikTeX/**本模板不支持CTeX套装**）：TeXLive2022

- 模板版本（在 `hithesis***.cls` 中的 `\ProvidesClass` 命令中的 `3.x.xx` 或 `3.xx` 即为版本号）：3.1c

## 描述bug具体信息

- 请给出完整的示例文件：

```latex
% 将 thesis.tex/report.tex 中的内容完整地放在这里
```
[reports.zip](https://github.com/hithesis/hithesis/files/11494448/reports.zip)

或将整个 `hitbook/chinese`, `reports` 或 `reportplus` 压缩后上传 `.zip` 文件

- 使用什么编译方式（`xelatex`/`latexmk`/`make thesis`）：xelatex
- 编译报错 or 编译结果与预期不符：与页眉有一道缝隙
- 

- 如果有编译报错，可以将报错信息截图粘贴到下面：

- 如果编译结果与预期不符：
  - 预期结果的截图
![屏幕截图 2023-05-17 132703](https://github.com/hithesis/hithesis/assets/23145786/288979bb-1a81-43c1-841f-e7857d047332)

  - 编译后的效果截图
![屏幕截图 2023-05-17 132315](https://github.com/hithesis/hithesis/assets/23145786/0bfd97aa-ff23-41b8-8233-d448711b30e6)

- 将编译后产生的 `.log` 文件上传到这里。
-

**Comment by syvshc** [comment]
指的是文字与页眉的间距吗？

**Comment by ltngiu** [comment]
> 指的是文字与页眉的间距吗？
是的

**Comment by ltngiu** [comment]
顺道，还有个首行缩进的问题，首行缩进只有1.5个字。

**Comment by ltngiu** [comment]
是的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: syvshc ***@***.***&gt;
发送时间: 2023年5月17日 13:32
收件人: hithesis/hithesis ***@***.***&gt;
抄送: Blitz ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [hithesis/hithesis] 深圳校区页眉问题 (Issue #177)





 
指的是文字与页眉的间距吗？

**Comment by syvshc** [comment]
> 顺道，还有个首行缩进的问题，首行缩进只有1.5个字。

这个可以在导言区设置 `\setlength{\parindent}{2\ccwd}`
