### ISSUE TITLE
如何实现定义等theorem缩进对齐？

### ISSUE THREAD

**Issue by umnooob** [hithesis/hithesis#180]
## 基本信息

- 校区（哈尔滨/威海/深圳？）：威海

- 学位（本/硕/博？）：本

- 论文类型（毕业论文/开题/中期/博后/English Version？）：毕业论文

- LaTeX 发行版（TeXLive 20xx/MikTeX/**本模板不支持CTeX套装**）：TeXLive 2022

- 模板版本（在 `hithesis***.cls` 中的 `\ProvidesClass` 命令中的 `3.x.xx` 或 `3.xx` 即为版本号）：v3.1c

## 想实现的效果
如何修改theoremstyle让定义可以与段落缩进对齐

![image](https://github.com/hithesis/hithesis/assets/41941089/72feafe9-169e-4469-b4d8-9dcaadbe8106)

**Comment by syvshc** [comment]
这是哪里规范要求的吗?

**Comment by umnooob** [comment]
> 这是哪里规范要求的吗?

当时老师要求的，并非学校层面的要求

之后我直接用段落替代了:)

如果麻烦的话直接close掉就行
