### ISSUE TITLE
chinese版本  中的英文目录没有左对齐 ，英文目录缺少appendix

### ISSUE THREAD

**Issue by szq976** [hithesis/hithesis#182]
**请不要主动关闭 issue，如果问题已经解决并推送到 [dev](https://github.com/hithesis/hithesis/tree/dev) 分支，该 issue 会被打上 `fixed in dev` 的标签，并在合并到 [master](https://github.com/hithesis/hithesis/tree/master) 分支后关闭。** 
## 基本信息

- 校区（哈尔滨/威海/深圳？）：哈尔滨

- 学位（本/硕/博？）：博

- 论文类型（毕业论文/开题/中期/博后/English Version？）：毕业论文

- 证据（与规范不符/与word模板不符？）：

- 证据所在网页（窝工规范或者word模板所在窝工官方网页）：

- LaTeX 发行版（TeXLive 20xx/MikTeX/**本模板不支持CTeX套装**）：

- 模板版本（在 `hithesis***.cls` 中的 `\ProvidesClass` 命令中的 `3.x.xx` 或 `3.xx` 即为版本号）：

## 描述模板不符合的具体信息
1.英文目录没有左对齐
2.英文目录缺少appendix

窝工在（规范/word模板中）第（xxx）行规定格式为：

如图：

hithesis的格式为

如图：

如码：

**Comment by syvshc** [comment]
"英文目录缺少 appendix" 是什么意思

**Comment by szq976** [comment]
英文目录中  没有附录部分的页码  （appendix  A  .....页码）

**Comment by szq976** [comment]
![FIF)8EVPBP@`EN9O@%6R8OM](https://github.com/hithesis/hithesis/assets/66050981/92ee963e-f369-45fc-a164-aea63062648f)
![F(@A6KQ(DBHIYT)PD40EP 4](https://github.com/hithesis/hithesis/assets/66050981/976a3b27-b9d8-497a-99af-ad92ef654d62)
我这里不知道怎么回事   没显示   我看看

**Comment by szq976** [comment]
![}~49D F)6Q9JWI$2K`DT`9](https://github.com/hithesis/hithesis/assets/66050981/65671c6d-7e3d-4615-bf94-c2741c3f87d3)
有appendix  刚才选择了本科书序。

**Comment by syvshc** [comment]
临时修改方案: 在 `hithesisbook.cls` 中找到

```tex
\RenewDocumentCommand{\chapter}{s o m o}{%
```

在这个定义中找到

```tex
      \addcontentsline{toe}{chapter}
        {%                                                <- 这里加一个 %
          \texorpdfstring
            {\bfseries\relax \hit@engtoc@chapapp \thechapter\hspace{0.5em}\ignorespaces #4}
            {\hit@engtoc@chapapp \thechapter\hspace{0.5em}\ignorespaces #4}
```
看看还有没有什么其他的问题, 一并改了

**Comment by szq976** [comment]
![Z_L@U~_VG~`P2G1{77)(_~U](https://github.com/hithesis/hithesis/assets/66050981/47ac57e6-8534-4005-90e7-99d2b88d5545)
有个报错问题

**Comment by syvshc** [comment]
这个问题我也在看, 如果写一个 `\cite` 就没报错了应该

**Comment by szq976** [comment]
好的

**Comment by szq976** [comment]
> 这个问题我也在看, 如果写一个 `\cite` 就没报错了应该

在哪里加\cite

**Comment by syvshc** [comment]
> 在哪里加\cite

先清除所有辅助文件, 然后保证文中有一个 `\cite`, 再重新编译即可.

**Comment by szq976** [comment]
不会弄   大佬发布一个不会报错的版本吧（emmm)

**Comment by szq976** [comment]
没问题了   刚才我把Chinese那个文件夹单独拿出来了   导致了报错    所以不能把某一个文件夹拿出来单独运行？

**Comment by szq976** [comment]
没问题了  懂了

**Comment by syvshc** [comment]
可以的, 并且我找到了原因: [ntheorem with thmmarks and standard options fails when thebibliography is empty](https://tex.stackexchange.com/questions/535950/ntheorem-with-thmmarks-and-standard-options-fails-when-thebibliography-is-empty)
具体表现为: 如果 `thebibliography` 环境为空 (文章中没有使用 `\cite` 命令来引用参考文献), 并且在该环境后有 `list` 类的环境 (如 `enumerate`, `itemize` 等), 就会导致一个 `Missing \item` 的错误, 最小工作示例如下:

```tex
\documentclass{article}
\usepackage[thmmarks]{ntheorem}
% \usepackage{ntheorem}
\begin{document}
hello
\begin{thebibliography}{0}

\end{thebibliography}
  \begin{enumerate}
    \item test
  \end{enumerate}
\end{document}
```

而你的论文里正常也不应该不存在 `\cite`, 所以通常情况下是没有问题的, 这个替换会在 `3.2a` 版本进行改动, 目前并没有产生实质的影响.

**Comment by szq976** [comment]
![ZN{RT15WV2BQF15ZU9W@Q5G](https://github.com/hithesis/hithesis/assets/66050981/f8a4d162-7bd8-458f-95ca-3453d27009aa)
怎么把文中的英文字体设置为times new roman

**Comment by syvshc** [comment]
> 怎么把文中的英文字体设置为times new roman

新的问题请新开 issue, 这个字体和 Times New Roman 非常接近, 除非覆盖比较, 一般是看不出差别的, 是有老师让你修改字体吗?
