### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by szq976** [hithesis/hithesis#184]
**请不要主动关闭 issue，如果问题已经解决并推送到 [dev](https://github.com/hithesis/hithesis/tree/dev) 分支，该 issue 会被打上 `fixed in dev` 的标签，并在合并到 [master](https://github.com/hithesis/hithesis/tree/master) 分支后关闭。** 
## 基本信息

- 校区（哈尔滨/威海/深圳？）：

- 学位（本/硕/博？）：

- 论文类型（毕业论文/开题/中期/博后/English Version？）：

- 证据（与规范不符/与word模板不符？）：

- 证据所在网页（窝工规范或者word模板所在窝工官方网页）：

- LaTeX 发行版（TeXLive 20xx/MikTeX/**本模板不支持CTeX套装**）：

- 模板版本（在 `hithesis***.cls` 中的 `\ProvidesClass` 命令中的 `3.x.xx` 或 `3.xx` 即为版本号）：

## 描述模板不符合的具体信息

窝工在（规范/word模板中）第（xxx）行规定格式为：

如图：

hithesis的格式为

如图：
![06W(4T 8QI10BPJ`BGK7 Y1](https://github.com/hithesis/hithesis/assets/66050981/620bcaf6-6907-43e9-b513-9b5d0158683c)

如码：

**Comment by syvshc** [comment]
#183 是我给自己写的，目前的模板不要进行定理类环境宏包的替换

**Comment by szq976** [comment]
明白了
