### ISSUE TITLE
目录中的原创声明和使用权限无法取消加粗

### ISSUE THREAD

**Issue by coffee8n24** [hithesis/hithesis#185]
## 描述bug类型

- 校区（哈尔滨/威海/深圳？）：哈尔滨

- 学位（本/硕/博？）：本

- 论文类型（毕业论文/开题/中期/博后/English Version？）：毕业论文

- LaTeX 发行版（TeXLive 20xx/MikTeX/**本模板不支持CTeX套装**）：TeXLive 2022

- 模板版本（在 `hithesis***.cls` 中的 `\ProvidesClass` 命令中的 `3.x.xx` 或 `3.xx` 即为版本号）：v3.1c-dev

## 描述bug具体信息
在thesis中将“chapterbold=false”写入后，目录中的原创声明和使用权限无法取消加粗。
<img width="704" alt="image" src="https://github.com/hithesis/hithesis/assets/88196799/c22716bb-db94-4e2f-a4d6-93310d1fe3db">
<img width="547" alt="image" src="https://github.com/hithesis/hithesis/assets/88196799/aa2fa320-396f-470a-8d56-f25b7b83f0d2">

**Comment by syvshc** [comment]
由于哈尔滨本科模板改动较大, 请在 dev 分支下载新的模板. 这个 issue 中提的问题在 解决了
