### ISSUE TITLE
v3.1c版本插入原创性声明扫描页后目录失去对应书签

### ISSUE THREAD

**Issue by RaleLee** [hithesis/hithesis#190]
## 描述bug类型

- 校区（哈尔滨/威海/深圳？）：哈尔滨

- 学位（本/硕/博？）：硕

- 论文类型（毕业论文/开题/中期/博后/English Version？）：毕业论文

- LaTeX 发行版（TeXLive 20xx/MikTeX/**本模板不支持CTeX套装**）：TeXLive 2019

- 模板版本（在 `hithesis***.cls` 中的 `\ProvidesClass` 命令中的 `3.x.xx` 或 `3.xx` 即为版本号）：dev-3.1c

## 描述bug具体信息

- 使用什么编译方式（`xelatex`/`latexmk`/`make thesis`）：xelatex\*1+bibtex+xelatex\*2
- 编译结果与预期不符：

    在未使用插入扫描版本的普通\authorization命令时，可以正确在目录中显示对应页码的书签名。
    但是使用\authorization[scan.pdf]命令后，无法正确显示

  - 预期结果的截图
![image](https://github.com/hithesis/hithesis/assets/31441192/af5a91b5-9118-44df-b07b-737fd014d723)

  - 编译后的效果截图
![image](https://github.com/hithesis/hithesis/assets/31441192/cf435097-6227-487f-aa1b-6aeef689504c)

**Comment by syvshc** [comment]
我这里使用 texlive 2023 对 3.1c 版本测试没有发现问题, 可以考虑更新一下 texlive :)

**Comment by RaleLee** [comment]
感谢大佬，我这里采取直接修改toc，然后只用一次xelatex编译的方法糊弄过去了

**Comment by RaleLee** [comment]
通过toc可以把目录改了，然后通过pdf软件可以把书签名加上去。
我这里简单记录一下，也许有同学用得上  : )

**Comment by syvshc** [comment]
我又试了一下, 3.1c 确实有问题, 但是最新版本已经修复了, 在 dev 分支.

**Comment by RaleLee** [comment]
按照大佬的修改建议，我将 dev 分支的 [commit 13953a4](https://github.com/hithesis/hithesis/commit/13953a47a32d24aa1c46a634d3d3d8a153f40b1a) 时的 **hithesis.dtx** 文件中的命令`\NewDocumentCommand{\authorization}` 复制到我的本地
```
\NewDocumentCommand{\authorization}{o}{%
  \IfNoValueTF{#1}{%
    \ifhit@bachelor\hit@authorization@bachelor\else\hit@authorization@other\fi
    }{%
    \ifhit@openright\cleardoublepage\else\clearpage\fi%
    \includepdf[fitpaper=true,pagecommand={%
  \thispagestyle{hit@empty}%
  \phantomsection\addcontentsline{toc}{chapter}{\ifhit@bachelor
%    \end{macrocode}
%
% \changes{v3.1b}{2022/06/06}{修改深圳校区原创性声明的目录标题。}
% \changes{v3.1d}{0000/00/00}{调整 \cmd{\fi} 的位置。}
% 深圳校区本科生目录中的原创性声明的部分为“原创性声明”，而不是 \cs{hit@declarename@bachelor}。
%    \begin{macrocode}
    \ifhit@shenzhen 原创性声明 \else  
    \hit@declarename@bachelor\fi\else\hit@authorization@ctitle\fi}%
  \ifhit@doctor%
%    \end{macrocode}
%
% \changes{v1.0.13}{2018/4/5}{添加\cs{texorpdfstring}命令去除书签中带有格式时的警告}
%    \begin{macrocode}
    \addcontentsline{toe}{chapter}{\texorpdfstring{\bfseries \hit@authorization@etitle}{\hit@authorization@etitle}}%
  \fi%
    }]{#1}%
  }%
}
```
并且再次进行编译模板
`lualatex hithesis.ins`
然后正常编译得到了正常的结果
`xelatex*1+bibtex+xelatex*2`
![image](https://github.com/hithesis/hithesis/assets/31441192/ded6ce06-dc98-4d69-80f2-186532da993f)
