### ISSUE TITLE
哈尔滨博士开题模板（example/hitart/reports)

### ISSUE THREAD

**Issue by jiejie567** [hithesis/hithesis#191]
## 描述bug类型

- 校区（哈尔滨/威海/深圳？）：哈尔滨

- 学位（本/硕/博？）：博

- 论文类型（毕业论文/开题/中期/博后/English Version？）：中期

- LaTeX 发行版（TeXLive 20xx/MikTeX/**本模板不支持CTeX套装**）：TeXLive 2023

- 模板版本（在 `hithesis***.cls` 中的 `\ProvidesClass` 命令中的 `3.x.xx` 或 `3.xx` 即为版本号）：v3.1c

## 描述bug具体信息 目录显示有问题

- 请给出完整的示例文件：

```latex
% 将 thesis.tex/report.tex 中的内容完整地放在这里
没有任何改动，所以不放了~
```

或将整个 `hitbook/chinese`, `reports` 或 `reportplus` 压缩后上传 `.zip` 文件

- 使用什么编译方式（`xelatex`/`latexmk`/`make thesis`）：xelatex
- 编译报错 or 编译结果与预期不符：编译结果与预期不符

- 如果有编译报错，可以将报错信息截图粘贴到下面：

- 如果编译结果与预期不符：
  - 预期结果的截图

  - 编译后的效果截图
![5DH2BGQ4KJG)XSX5K6)F@T2](https://github.com/hithesis/hithesis/assets/57585288/c58ee179-1241-4937-9c9f-34ae5331e07f)

- 将编译后产生的 `.log` 文件上传到这里。
- [report.log](https://github.com/hithesis/hithesis/files/11676655/report.log)

**Comment by jiejie567** [comment]
是的，是间距问题





------------------ 原始邮件 ------------------
发件人: Melody ***@***.***&gt;
发送时间: 2023年6月7日 22:15
收件人: hithesis/hithesis ***@***.***&gt;
抄送: jiejie567 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [hithesis/hithesis] 哈尔滨博士开题模板（example/hitart/reports) (Issue #191)

**Comment by jiejie567** [comment]
> 试试这个，我是手动改的，没有直接修改模板。
> 
> ```
> \usepackage{tocloft}
> \renewcommand\cftsecafterpnum{\vskip10pt}
> \renewcommand\cftsubsecafterpnum{\vskip10pt} 
> \renewcommand\cftsubsubsecafterpnum{\vskip10pt}
> ```
> 
> 我是凭感觉给的`\vskip`，不太清楚具体标准，如果有话可以纠正

感谢，但是我copy到文中报错
![image](https://github.com/hithesis/hithesis/assets/57585288/bcc1629f-2178-4ef7-9a4a-077127ecf1a2)
还请指教，我对于latex比较小白

**Comment by syvshc** [comment]
> 应该是和模板的subfigure冲突了，我在模板中注释掉了对subfigure的使用。

![image](https://github.com/hithesis/hithesis/assets/38098591/4c0660b5-fe20-4f28-abd5-9047a9b3c251)

可以 `\usepackage[subfigure]{tocloft}`, 确实这个东西已经老了, 打算在下一个大版本的时候把它弄掉……

**Comment by jiejie567** [comment]
谢谢两位大佬，你们提供的方法有效。除此之外 ”目录“没有居中，没有没有页眉

**Comment by jiejie567** [comment]
请问下行距还是有问题，该怎么修改呢？
![image](https://github.com/hithesis/hithesis/assets/57585288/f1d92c99-2b63-4416-9794-3a1505457b7b)


> 试试这个，我是手动改的，没有直接修改模板。
> 
> ```
> \usepackage{tocloft}
> \renewcommand\cftsecafterpnum{\vskip10pt}
> \renewcommand\cftsubsecafterpnum{\vskip10pt} 
> \renewcommand\cftsubsubsecafterpnum{\vskip10pt}
> ```
> 
> 我是凭感觉给的`\vskip`，不太清楚具体标准，如果有话可以纠正

**Comment by syvshc** [comment]
@jiejie567 在 cls 文件里找 `\ctexset` 里面有7.5bp这种长度，自行修改一下

**Comment by jiejie567** [comment]
> @jiejie567 在 cls 文件里找 `\ctexset` 里面有7.5bp这种长度，自行修改一下

已解决，感谢如此快的回复！

**Comment by ArrogantL** [comment]
试了大半天，还是大佬们说的解决方案好用：
在report.tex文件里面修改，
找到这一行\documentclass[fontset=fandol,toc=true,type=doctor,stage=opening,campus=harbin]{hithesisart}

下面添加以下四行，其中后三行调整目录格式
\usepackage[subfigure]{tocloft}
\renewcommand\cftsecafterpnum{\vskip10pt}
\renewcommand\cftsubsecafterpnum{\vskip10pt} 
\renewcommand\cftsubsubsecafterpnum{\vskip10pt}

**Comment by fatdragonsxh** [comment]
@jiejie567 你好，想咨询一下这里的ctexset修改有比较准确的数字吗

**Comment by syvshc** [comment]
> @jiejie567 你好，想咨询一下这里的ctexset修改有比较准确的数字吗

```latex
\ctexset{%
  section={
    afterindent=true,
    beforeskip={7.5mm},%上下空0.5行
    afterskip={7.5mm},
    format={\heiti\xiaosan[1.25]},
    aftername=\enspace,
    fixskip=true,
    break={},
  },
  subsection={
    afterindent=true,
    beforeskip={6.5mm},
    afterskip={6.5mm},
    format={\heiti\sihao[1.25]},
    aftername=\enspace,
    fixskip=true,
    break={},
  },
  subsubsection={
    afterindent=true,
    beforeskip={3mm},
    afterskip={3mm},
    format={\heiti\normalsize},
    aftername=\enspace,
    fixskip=true,
    break={},
  },
  paragraph/afterindent=true,
  subparagraph/afterindent=true
}
```

这是我本科毕设的, 仅供参考
