### ISSUE TITLE
in science在哪里加

### ISSUE THREAD

**Issue by szq976** [hithesis/hithesis#195]
**请不要主动关闭 issue，如果问题已经解决并推送到 [dev](https://github.com/hithesis/hithesis/tree/dev) 分支，该 issue 会被打上 `fixed in dev` 的标签，并在合并到 [master](https://github.com/hithesis/hithesis/tree/master) 分支后关闭。** 
## 基本信息

- 校区（哈尔滨/威海/深圳？）：哈尔滨

- 学位（本/硕/博？）：博

- 论文类型（毕业论文/开题/中期/博后/English Version？）：毕业论文

- 证据（与规范不符/与word模板不符？）：

- 证据所在网页（窝工规范或者word模板所在窝工官方网页）：

- LaTeX 发行版（TeXLive 20xx/MikTeX/**本模板不支持CTeX套装**）：

- 模板版本（在 `hithesis***.cls` 中的 `\ProvidesClass` 命令中的 `3.x.xx` 或 `3.xx` 即为版本号）：

## 描述模板不符合的具体信息  in science在哪里加

窝工在（规范/word模板中）第（xxx）行规定格式为：
![image](https://github.com/hithesis/hithesis/assets/66050981/6f123686-768a-4546-a256-e323f88e0c15)

如图：

hithesis的格式为
![image](https://github.com/hithesis/hithesis/assets/66050981/53b6c75d-466b-4662-8850-01e3cd5064aa)

如图：

如码：

**Comment by szq976** [comment]
？

**Comment by szq976** [comment]
在吗

**Comment by syvshc** [comment]
提供一下 word 版本的官方链接

**Comment by szq976** [comment]
这是我们学院的要求   参见https://kns.cnki.net/kcms2/article/abstract?v=3uoqIhG8C447WN1SO36whLpCgh0R0Z-ia63qwICAcC3-s4XdRlECrbqX9w4Y4g_opBty4OAcayxgwHA3da6Zcsn7oit6UNZj&uniplatform=NZKPT


word官方链接http://hitgs.hit.edu.cn/2021/0513/c3425a254242/page.htm

**Comment by syvshc** [comment]
![image](https://github.com/hithesis/hithesis/assets/38098591/da8eb0ac-d128-4449-b9b3-54846463e330)
官方模板中没有 in Science, 自行修改的话可以在 `hithesisbook.cls` 中的

```tex
      \begin{center}
        \ifboolexpr{bool {hit@shenzhen} and bool {hit@master}}
          {%
            Dissertation for the Master Degree
          }
          {%
            \ifboolexpr{bool {hit@harbin} and (bool {hit@master} or bool {hit@doctor})}
              {Dissertation for the {\hit@exueweier} Degree in \hit@exueke}         % <- 这里加一个 in \hit@exueke, 或者直接写 in Science
              {Dissertation for the {\hit@exueweier} Degree in \hit@exueke}
          }
      \end{center}
```

**Comment by szq976** [comment]
欧克
