### ISSUE TITLE
论文模板与新amsthm.sty中theoremstyle重复定义

### ISSUE THREAD

**Issue by Windaway** [hithesis/hithesis#198]
## 描述bug类型

- 校区（哈尔滨/威海/深圳？）：

- 学位（本/硕/博？）：

- 论文类型（毕业论文/开题/中期/博后/English Version？）：

- LaTeX 发行版（TeXLive 20xx/MikTeX/**本模板不支持CTeX套装**）：

- 模板版本（在 `hithesis***.cls` 中的 `\ProvidesClass` 命令中的 `3.x.xx` 或 `3.xx` 即为版本号）：

## 描述bug具体信息

- 请给出完整的示例文件：

```latex
% 将 thesis.tex/report.tex 中的内容完整地放在这里

```

或将整个 `hitbook/chinese`, `reports` 或 `reportplus` 压缩后上传 `.zip` 文件

- 使用什么编译方式（`xelatex`/`latexmk`/`make thesis`）：xelatex
- 编译报错 or 编译结果与预期不符：编译报错 

- 如果有编译报错，可以将报错信息截图粘贴到下面：

![image](https://github.com/hithesis/hithesis/assets/4530735/28b43558-af42-402e-bf92-62b59d437d8f)

- 如果编译结果与预期不符：
  - 预期结果的截图

  - 编译后的效果截图

- 将编译后产生的 `.log` 文件上传到这里。

**Comment by syvshc** [comment]
请提供你的使用方法, 以及模板的版本号, 阶段, 校区等信息, 以及 新 amsthm 的版本号

**Comment by Windaway** [comment]
使用默认release中的chinese book配置，无修改。
环境为目前miktex 23. texstudio 4.6.2 在windows下默认安装。 使用texstudio+xelatex编译。之前电脑老环境正常那时是miktex22
amsthm \ProvidesPackage{amsthm}[2020/05/29 v2.20.6]

**Comment by Windaway** [comment]
当前使用的thesis依然有问题：
% !Mode:: "TeX:UTF-8"
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%          ,
%      /\^/`\
%     | \/   |                CONGRATULATIONS!
%     | |    |             SPRING IS IN THE AIR!
%     \ \    /                                                _ _
%      '\\//'                                               _{ ' }_
%        ||                     hithesis v3                { `.!.` }
%        ||                                                ',_/Y\_,'
%        ||  ,                   dustincys                   {_,_}
%    |\  ||  |\          Email: yanshuoc@gmail.com             |
%    | | ||  | |            https://yanshuo.site             (\|  /)
%    | | || / /                                               \| //
%    \ \||/ /       https://github.com/dustincys/hithesis      |//
%      `\\//`   \\   \./    \\ /     //    \\./   \\   //   \\ |/ /
%     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\documentclass[fontset=fandol,type=doctor,campus=harbin]{hithesisbook}
%\documentclass[fontset=fandol,type=bachelor,campus=harbin]{hithesisbook}
% 此处选项中不要有空格
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 必填选项
% type=doctor
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 选填选项（选填选项的缺省值已经尽可能满足了大多数需求，除非明确知道自己有什么
% 需求）
% campus=shenzhen|weihai|harbin
%   含义：校区选项，默认harbin
% glue=true|false
%   含义：由于我工规范中要求字体行距在一个闭区间内，这个选项为true表示tex自
%   动选择，为false表示区间内一个最接近版心要求行数的要求的默认值，缺省值为
%   false。
% tocfour=true|false
%   含义：是否添加第四级目录，只对本科文科个别要求四级目录有效，缺省值为
%   false
% fontset=windows|mac|ubuntu|fandol|adobe
%   含义：设置字体，若不指定会自动识别系统，然后设置字体。fandol是开源字体，自行
%   下载安装后设置使用。windows是中易字库，窝工默认常用字体，绝对没毛病。mac和
%   ubuntu 默认分别是华文和思源字库，理论上用什么字库都行。后两种字库的安装方法
%   到谷歌上百度一下什么都有了。Linux非ubuntu发行版、非x86架构机器等如何运行可到
%   github issue上讨论。
% tocblank=true|false
%   含义：目录中第一章之前，是否加一行空白。缺省值为true。
% chapterhang=true|false
%   含义：目录的章标题是否悬挂居中，规范中要求章标题少于15字，所以这个选项
%   有无没什么用，除了特殊需求。缺省值为true。
% fulltime=true|false
%   含义：是否全日制，缺省值为true。非全日制如同等学力等，要在cover中设置类
%   型，封面中不同格式
% subtitle=true|false
%   含义：论文题目是否含有副标题，缺省值为false，如果有要在cover中设置副标
%   题内容，封面中显示。
% newgeometry=one|two|no
%   含义：规范中的自相矛盾之处，版芯是否包含页眉页脚，旧方法是按照包含页眉
%   页脚来设置。该选项是多选选项，如果设置为no，则版新为旧模板的版芯设置方法，
%   如果设置该选项one或two，分别对应两种页眉页码对应版芯线的相对位置。第一种
%   是严格按照规范要求，难看。第二种微调了页眉页码位置，好一点。默认two。
% debug=true|false
%   含义：是否显示版芯框和行号，用来调试。默认否。
% openright=true|false
%   含义：博士论文是否要求章节首页必须在奇数页，此选项不在规范要求中，按个
%   人喜好自行决定。 默认否。注意，窝工的默认情况是打印版博士论文要求右翻页
%   ，电子版要求非右翻页且无空白页。如果想DIY（或身不由己DIY）在什么地方右
%   翻页，将这个选项设置为false，然后在目标位置添加`\cleardoublepage`命令即
%   可。
% library=true|false
%   含义：是否为提交到图书馆的电子版。默认否。注意：如果设置成true，那么
%   openright选项将被强制转换为false。
% capcenterlast=true|false
%   含义：图题、表题最后一行是否居中对齐（我工规范要求居中，但不要求居中对
%   齐），此选项不在规范要求中，按个人喜好自行决定。默认否。
% subcapcenterlast=true|false
%   含义：子图图题最后一行是否居中对齐（我工规范要求居中，但不要求居中对齐
%   ），此选项不在规范要求中，按个人喜好自行决定。默认否。
% absupper=true|false
%   含义：中文目录中的英文摘要在中文目录中的大小写样式歧义，在规范中要求首
%   字母大写，在work样例中是全大写。该选项控制是否全大写。默认否。
% bsmainpagenumberline=true|false
%   含义：由于本科生论文官方模板的页码和页眉格式混乱，提供这个选项自定义设
%   置是否在正文中显示页码横线，默认显示。
% bsfrontpagenumberline=true|false
%   含义：由于本科生论文官方模板的页码和页眉格式混乱，提供这个选项自定义设
%   置是否在前文中显示页码横线，默认显示。
% bsheadrule=true|false
%   含义：由于本科生论文官方模板的页码和页眉格式混乱，提供这个选项自定义设
%   置是否显示页眉横线，默认显示。
% splitbibitem=true|false
%   含义：参考文献每一个条目内能不能断页，应广大刀客要求添加。默认否。
% newtxmath=true|false
%   含义：数学字体是否使用新罗马。默认是。
% chapterbold=true|false
%   含义：本科生章标题在目录和正文中是否加粗
% engtoc=true
%   含义：非博士生需要添加英文目录的，手动添加，如果是博士，此开关无效
% zijv=word|regu
%   含义：字距设置为规范规定33个字还是word中34个字。默认regu。
% citetwo=comma|endash
%   含义：相邻两个参考文献中的连接符是由逗号：[1,2]还是短线[1-2]。默认endash
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% [linesnumbered,ruled]
\usepackage{hithesis}
%\usepackage{bm}

\usepackage{tabularx}
\usepackage{algorithm2e}

\newcolumntype{Y}{>{\centering\arraybackslash}X}
\newcolumntype{Z}{>{\centering\let\newline\\\arraybackslash\hspace{0pt}}X}
\newcolumntype{L}{>{\RaggedRight\hangafter=1\hangindent=0em}X}

\graphicspath{{figures/}}

\begin{document}
\frontmatter
\input{front/cover} % 封面
\makecover
%\input{front/denotation}%物理量名称表,符合规范为主，有要求添加
\tableofcontents %目录
\mainmatter
%\include{body/regu}
\include{body/introduction}
\include{body/chap1}
\include{body/chap2}
\include{body/chap3}
\include{body/chap4}
\backmatter
\include{back/conclusion}   % 结论
%\bibliographystyle{gbt7714-numerical}
% \bibliographystyle{hitszthesis} % 深圳校区的同学请使用 hitszthesis 文献样式
\bibliographystyle{hithesis} %理论上2020最新要求文献样式GB/T 7714—2015，但若院系要求文献英文作者不全大写，可改用hithesis文献样式
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%-- 注意：以下本硕博、博后书序不一致 --%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 本科书序（哈尔滨、深圳校区）
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%\bibliography{reference} % 参考文献
%\authorization %授权
% \authorization[scan.pdf] %添加扫描页的命令，与上互斥
%\include{back/acknowledgements} %致谢
%\begin{appendix}%附录
%\input{back/appendix01}%本科生翻译论文
%\end{appendix}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 本科书序（威海校区）
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% \authorization %授权
% % \authorization[scan.pdf] %添加扫描页的命令，与上互斥
% \bibliography{reference} % 参考文献
% \include{back/acknowledgements} %致谢
% \begin{appendix}%附录
% \input{back/appendix01}%本科生翻译论文
% \end{appendix}
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 硕博书序
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 % 参考文献
\bibliography{reference} % 参考文献
\begin{appendix}%附录
\input{back/appA.tex}
\end{appendix}
\include{back/publications}    % 所发文章
\include{back/ceindex}    % 索引, 根据自己的情况添加或者不添加，选择自动添加或者手工添加。
\authorization %授权
%\authorization[scan.pdf] %添加扫描页的命令，与上互斥
\include{back/acknowledgements} %致谢
\include{back/resume}          % 博士学位论文有个人简介
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 博后书序
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% \bibliography{reference} % 参考文献
% \include{back/acknowledgements} %致谢
% \include{back/doctorpublications}    % 所发文章
% \include{back/publications}    % 所发文章
% \include{back/resume}          % 博士学位论文有个人简介
% \include{back/correspondingaddr} %通信地址
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\end{document}
% Local Variables:
% TeX-engine: xetex
% End:

**Comment by syvshc** [comment]
等我搞个 miktex 测试一下吼, 我这里没有 miktex 的环境

**Comment by Windaway** [comment]
好，不过report下可以，book下出错。提示都是重复定义。

**Comment by Windaway** [comment]
我用inc重新编译然后xelatex手动编译默认的chinese book
```
D:\theis\hithesis-3.1c>cd D:\theis\hithesis-3.1c\examples\hitbook\chinese

D:\theis\hithesis-3.1c\examples\hitbook\chinese>xelatex -shell-escape thesis.tex
This is XeTeX, Version 3.141592653-2.6-0.999995 (MiKTeX 23.5) (preloaded format=xelatex.fmt)
 \write18 enabled.
entering extended mode
(thesis.tex
LaTeX2e <2023-06-01> patch level 1
L3 programming layer <2023-06-30>
(hithesisbook.cls
Document Class: hithesisbook 2023/04/16 v3.1c Harbin Institute of Technology Th
esis Template
(d:\MiKTeX\tex/latex/kvoptions\kvoptions.sty
(d:\MiKTeX\tex/latex/graphics\keyval.sty)
(d:\MiKTeX\tex/generic/ltxcmds\ltxcmds.sty)
(d:\MiKTeX\tex/latex/kvsetkeys\kvsetkeys.sty))
(d:\MiKTeX\tex/latex/base\ifthen.sty) (d:\MiKTeX\tex/latex/ctex\ctexbook.cls
(d:\MiKTeX\tex/latex/ctex/config\ctexbackend.cfg)
(d:\MiKTeX\tex/latex/l3kernel\expl3.sty
(d:\MiKTeX\tex/latex/l3backend\l3backend-xetex.def))
Document Class: ctexbook 2022/07/14 v2.5.10 Chinese adapter for class book (CTE
X)
(d:\MiKTeX\tex/latex/ctex\ctexhook.sty) (d:\MiKTeX\tex/latex/ctex\ctexpatch.sty
) (d:\MiKTeX\tex/latex/base\fix-cm.sty (d:\MiKTeX\tex/latex/base\ts1enc.def))
(d:\MiKTeX\tex/latex/ctex/config\ctexopts.cfg)
(d:\MiKTeX\tex/latex/base\book.cls
Document Class: book 2023/05/17 v1.4n Standard LaTeX document class
(d:\MiKTeX\tex/latex/base\bk12.clo))
(d:\MiKTeX\tex/latex/ctex/engine\ctex-engine-xetex.def
(d:\MiKTeX\tex/xelatex/xecjk\xeCJK.sty
(d:\MiKTeX\tex/latex/l3packages/xtemplate\xtemplate.sty)
(d:\MiKTeX\tex/latex/fontspec\fontspec.sty
(d:\MiKTeX\tex/latex/l3packages/xparse\xparse.sty)
(d:\MiKTeX\tex/latex/fontspec\fontspec-xetex.sty
(d:\MiKTeX\tex/latex/base\fontenc.sty)
(d:\MiKTeX\tex/latex/fontspec\fontspec.cfg)))
(d:\MiKTeX\tex/xelatex/xecjk\xeCJK.cfg)))
(d:\MiKTeX\tex/latex/zhnumber\zhnumber.sty
(d:\MiKTeX\tex/latex/zhnumber\zhnumber-utf8.cfg))
(d:\MiKTeX\tex/latex/ctex/scheme\ctex-scheme-plain-book.def)
(d:\MiKTeX\tex/latex/ctex\ctex-cs4size.clo)
(d:\MiKTeX\tex/latex/ctex/fontset\ctex-fontset-fandol.def

Package fontspec Warning: Font "FandolSong-Regular" does not contain requested
(fontspec)                Script "CJK".

)) (d:\MiKTeX\tex/latex/ctex/config\ctex.cfg)
(d:\MiKTeX\tex/latex/etoolbox\etoolbox.sty)
(d:\MiKTeX\tex/generic/iftex\ifxetex.sty (d:\MiKTeX\tex/generic/iftex\iftex.sty
)) (d:\MiKTeX\tex/latex/amsmath\amsmath.sty
For additional information on amsmath, use the `?' option.
(d:\MiKTeX\tex/latex/amsmath\amstext.sty
(d:\MiKTeX\tex/latex/amsmath\amsgen.sty))
(d:\MiKTeX\tex/latex/amsmath\amsbsy.sty)
(d:\MiKTeX\tex/latex/amsmath\amsopn.sty))
(d:\MiKTeX\tex/latex/ntheorem\ntheorem.sty
Style `ntheorem', Version 1.33 <2011/08/15>
) (d:\MiKTeX\tex/latex/amsfonts\amssymb.sty
(d:\MiKTeX\tex/latex/amsfonts\amsfonts.sty))
(d:\MiKTeX\tex/latex/newtx\TeXGyreTermesX.fontspec)
(d:\MiKTeX\tex/latex/newtx\newtxmath.sty
`newtxmath' v1.72, 2023/07/19 Math macros based originally on txfonts (msharpe)
(d:\MiKTeX\tex/latex/xkeyval\xkeyval.sty
(d:\MiKTeX\tex/generic/xkeyval\xkeyval.tex
(d:\MiKTeX\tex/generic/xkeyval\xkvutils.tex)))
(d:\MiKTeX\tex/latex/oberdiek\centernot.sty)
(d:\MiKTeX\tex/generic/binhex\binhex.tex)
(d:\MiKTeX\tex/latex/amscls\amsthm.sty

! LaTeX Error: Command \theoremstyle already defined.
               Or name \end... illegal, see p.192 of the manual.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...

l.66 }

?

```

**Comment by syvshc** [comment]
好了, 我找到问题了, 鉴定为 `newtxmath` xx. 这个东西引发过好多问题了……
在 miktex 最新的库中,  `newtxmath` 的更新日期为 2023/7/19, 版本号为 1.72, 在这个版本里有这么个东西
```tex
\DeclareOption{amsthm}{\ntx@amsthmtrue}
\ntx@amsthmtrue    % <- 在这里

\ExecuteOptions{%
amssymbols,uprightGreek,nosubscriptcorrection}
\ProcessOptions\relax


\newif\iftx@lbtn
\iftx@libertine\tx@lbtntrue\else\iftx@libertinus%
\tx@lbtntrue\fi\fi

\let\ntxmath@scale\tx@scale

\ifntx@amsthm
  \RequirePackage{amsthm}
  \typeout{amsthm loaded}
\else
    \typeout{amsthm NOT loaded}
\fi
```
在这个版本中默认加载了 `amsthm` 宏包, 而由于 `hithesis` 用的是 `ntheorem` 宏包, 所以出现了定义冲突, 可以自行删除 `\ntx@amsthmtrue` 这句, 或者改用 TeXLive（
在最新的 2023/7/30 更新的 `newtxmath` (v1.723) 中, 已经没有这句话了.

**Comment by Windaway** [comment]
好了 谢谢你，我试试texlive
