### ISSUE TITLE
哈尔滨本科毕设开题报告专业名称过长问题

### ISSUE THREAD

**Issue by TomHedwig** [hithesis/hithesis#199]
## 基本信息

- 校区（哈尔滨/威海/深圳？）：哈尔滨

- 学位（本/硕/博？）：本

- 论文类型（毕业论文/开题/中期/博后/English Version？）：开题

- LaTeX 发行版（TeXLive 20xx/MikTeX/**本模板不支持CTeX套装**）：TeX Live  2023

- 模板版本（在 `hithesis***.cls` 中的 `\ProvidesClass` 命令中的 `3.x.xx` 或 `3.xx` 即为版本号）：v3.1c

## 想实现的效果

您好！

在写开题报告时，发现封面的专业名称在11字以下时可以保持在横线范围内，如下图所示：

![Snipaste_2023-09-19_08-40-24](https://github.com/hithesis/hithesis/assets/74413827/20da3eab-bb2f-4c06-8297-d040ffec99da)

但是当专业名称的字数再增加时，就会出现超出下方横线乃至于前面的“专业”相重叠的情况，如下图所示：

![Snipaste_2023-09-19_08-44-00](https://github.com/hithesis/hithesis/assets/74413827/4ab0f974-901b-4075-996c-28d5783b168a)

![Snipaste_2023-09-19_08-45-48](https://github.com/hithesis/hithesis/assets/74413827/e7cd6c4d-6ff5-4d4a-99f2-b62315dae5b4)

请问如何做才能使这种长专业名称也能较好地保持在横线范围中？希望您能给出一些建议，十分感谢！

**Comment by syvshc** [comment]
现在这个专业名字都这么长了吗……我看看怎么改哈

**Comment by syvshc** [comment]
在 `hithesisart.cls` 中搜索 `\newcommand{\hit@report@titlepage@bachelor}`
在定义中找到 `\parbox[b][6cm][t]{\textwidth}`, 把这一段替换为

```tex
\parbox[b][6cm][t]{\textwidth}{
    \begin{center}\songti\sanhao
      \renewcommand{\arraystretch}{2.1}
    \newlength\subject@length                 % <- 新增
    \newlength\tmp@length                     % <- 新增
    \settowidth{\tmp@length}{\hit@csubject}                 % <- 新增
    \setlength{\subject@length}{\ifdim\tmp@length>6.1cm\tmp@length \else 6.1cm \fi}                  % <- 新增
    % 下面把 6.1cm 改成了 \subject@length 了
    \begin{tabular}{l@{\ \ }c}
      \textbf{\hit@bachelor@cmajortitle} & \underline{\makebox[\subject@length]{\textbf{\hit@csubject}}}\\ 
      \textbf{\hit@bachelor@cstudenttitle} & \underline{\makebox[\subject@length]{\textbf{\hit@cauthor}}}\\
      \textbf{\hit@bachelor@cstudentidtitle} & \underline{\makebox[\subject@length]{\textbf{\hit@cstudentid}}}\\
      \ifhit@weihai % 威海校区特有
        \textbf{\hit@bachelor@cclass} & \underline{\makebox[\subject@length]{\textbf{\hit@cclassid}}}\\
      \fi
      \textbf{\hit@bachelor@csupervisortitle} & \underline{\makebox[\subject@length]{\textbf{\hit@csupervisor}}}\\
      \textbf{\hit@bachelor@cdatetitle} & \underline{\makebox[\subject@length]{\textbf{\hit@cdate}}}\\
    \end{tabular}\renewcommand{\arraystretch}{1}
  \end{center}
  }
  \vfill
  \ifhit@weihai
    \relax
  \else
    \hit@harbin@bachelor@schoolbottommark
  \fi
}
```

再看看还有没有啥问题

**Comment by TomHedwig** [comment]
已经解决了，暂时没有别的问题，非常感谢您！

**Comment by TomHedwig** [comment]
您好！除了本科开题报告外，在毕设论文中也存在这个问题：

![Snipaste_2023-09-20_21-42-06](https://github.com/hithesis/hithesis/assets/74413827/542cf8eb-9134-4968-ad5a-b32ad5461912)

然后用您的方法，结合 #60 中的数据，将6.1cm改成7.7cm就可以得到这样的结果：

![Snipaste_2023-09-20_21-41-11](https://github.com/hithesis/hithesis/assets/74413827/881d3e3f-7580-4055-a729-de6f9010198f)

**Comment by TomHedwig** [comment]
具体的是在 hithesisbook.cls 中（1229行左右）将

`\parbox[t][14.2cm][b]{\textwidth}
    {\heiti\xiaosan
      \begin{center} \renewcommand{\arraystretch}{2.5} \heiti
  \setlength{\hit@title@width}{5.5em}
  \begin{tabular}%
    {l@{\ \  }>{\ifhit@shenzhen \normalfont\songti \else \fi}c}
    \ifboolexpr{bool {hit@shenzhen} and bool {hit@bachelor}}
      {%
        {\xiaoer  \hit@put@title{\hit@bachelor@cthesistitle}}
          & \underline{\makebox[6.1cm][l]{%
            \settowidth{\hit@ctitleonelength}{\xiaoer \hit@ctitleone}%
            \ifdim\hit@ctitleonelength>6.1cm\sanhao\else\xiaoer\fi\hit@ctitleone}}\\
          & \underline{\makebox[6.1cm][l]{%
            \settowidth{\hit@ctitletwolength}{\xiaoer \hit@ctitletwo}%
            \ifdim\hit@ctitletwolength>6.1cm\sanhao\else\xiaoer\fi\hit@ctitletwo}}\\
          & \\
        {\hit@put@title{\hit@bachelor@cstudenttitle}}
          & \underline{\makebox[6.1cm][l]{\hit@cauthor}}\\
        {\hit@put@title{\hit@bachelor@cstudentidtitle}}
          & \underline{\makebox[6.1cm][l]{\hit@cstudentid}}\\
        {\hit@put@title{\hit@bachelor@caffiltitlesz}}
          & \underline{\makebox[6.1cm][l]{\hit@caffil}}\\
        {\hit@put@title{\hit@bachelor@cmajortitle}}
          & \underline{\makebox[6.1cm][l]{\hit@csubject}}\\
        {\hit@put@title{\hit@bachelor@csupervisortitle}}
          & \underline{\makebox[6.1cm][l]{\hit@csupervisor}}\\
        {\hit@put@title{\hit@cdatetitle}}
          & \underline{\makebox[6.1cm][l]{\hit@cdate}}
      }
      {%
        {\xiaoer  \hit@put@title{\hit@bachelor@cthesistitle}}
          & \underline{\makebox[6.1cm]{%
            \settowidth{\hit@ctitleonelength}{\xiaoer \hit@ctitleone}%
            \ifdim\hit@ctitleonelength>6.1cm\sanhao\else\xiaoer\fi\hit@ctitleone}}\\
          & \underline{\makebox[6.1cm]{%
            \settowidth{\hit@ctitletwolength}{\xiaoer \hit@ctitletwo}%
            \ifdim\hit@ctitletwolength>6.1cm\sanhao\else\xiaoer\fi\hit@ctitletwo}}\\
          & \\
        {\hit@put@title{\hit@bachelor@cmajortitle}}
          & \underline{\makebox[6.1cm]{\hit@csubject}}\\
        {\hit@put@title{\hit@bachelor@cstudentidtitle}}
          & \underline{\makebox[6.1cm]{\hit@cstudentid}}\\
        {\hit@put@title{\hit@bachelor@cstudenttitle}}
          & \underline{\makebox[6.1cm]{\hit@cauthor}}\\
        {\hit@put@title{\hit@bachelor@csupervisortitle}}
          & \underline{\makebox[6.1cm]{\hit@csupervisor}}\\
        {\hit@put@title{\hit@cdatetitle}}
          & \underline{\makebox[6.1cm]{\hit@cdate}}
      }
  \end{tabular} \renewcommand{\arraystretch}{1}
      \end{center}
    }`

改为

`\parbox[t][14.2cm][b]{\textwidth}
    {\heiti\xiaosan
      \begin{center} \renewcommand{\arraystretch}{2.5} \heiti
        % <- 新增
        \newlength\subject@length
        \newlength\tmp@length
        \settowidth{\tmp@length}{\hit@csubject}
        \setlength{\subject@length}{\ifdim\tmp@length>7.7cm\tmp@length \else 7.7cm \fi}
        \setlength{\hit@title@width}{5.5em}
        % <- 新增
        \begin{tabular}%
          {l@{\ \  }>{\ifhit@shenzhen \normalfont\songti \else \fi}c}
          \ifboolexpr{bool {hit@shenzhen} and bool {hit@bachelor}}
          {%
          {\xiaoer  \hit@put@title{\hit@bachelor@cthesistitle}}
          & \underline{\makebox[\subject@length][l]{%
            \settowidth{\hit@ctitleonelength}{\xiaoer \hit@ctitleone}%
            \ifdim\hit@ctitleonelength>\subject@length\sanhao\else\xiaoer\fi\hit@ctitleone}}\\
          & \underline{\makebox[\subject@length][l]{%
            \settowidth{\hit@ctitletwolength}{\xiaoer \hit@ctitletwo}%
            \ifdim\hit@ctitletwolength>\subject@length\sanhao\else\xiaoer\fi\hit@ctitletwo}}\\
          & \\
          {\hit@put@title{\hit@bachelor@cstudenttitle}}
          & \underline{\makebox[\subject@length][l]{\hit@cauthor}}\\
          {\hit@put@title{\hit@bachelor@cstudentidtitle}}
          & \underline{\makebox[\subject@length][l]{\hit@cstudentid}}\\
          {\hit@put@title{\hit@bachelor@caffiltitlesz}}
          & \underline{\makebox[\subject@length][l]{\hit@caffil}}\\
          {\hit@put@title{\hit@bachelor@cmajortitle}}
          & \underline{\makebox[\subject@length][l]{\hit@csubject}}\\
          {\hit@put@title{\hit@bachelor@csupervisortitle}}
          & \underline{\makebox[\subject@length][l]{\hit@csupervisor}}\\
          {\hit@put@title{\hit@cdatetitle}}
          & \underline{\makebox[\subject@length][l]{\hit@cdate}}
        }
        {%
        {\xiaoer  \hit@put@title{\hit@bachelor@cthesistitle}}
          & \underline{\makebox[\subject@length]{%
            \settowidth{\hit@ctitleonelength}{\xiaoer \hit@ctitleone}%
            \ifdim\hit@ctitleonelength>\subject@length\sanhao\else\xiaoer\fi\hit@ctitleone}}\\
          & \underline{\makebox[\subject@length]{%
            \settowidth{\hit@ctitletwolength}{\xiaoer \hit@ctitletwo}%
            \ifdim\hit@ctitletwolength>\subject@length\sanhao\else\xiaoer\fi\hit@ctitletwo}}\\
          & \\
          {\hit@put@title{\hit@bachelor@cmajortitle}}
          & \underline{\makebox[\subject@length]{\hit@csubject}}\\
          {\hit@put@title{\hit@bachelor@cstudentidtitle}}
          & \underline{\makebox[\subject@length]{\hit@cstudentid}}\\
          {\hit@put@title{\hit@bachelor@cstudenttitle}}
          & \underline{\makebox[\subject@length]{\hit@cauthor}}\\
          {\hit@put@title{\hit@bachelor@csupervisortitle}}
          & \underline{\makebox[\subject@length]{\hit@csupervisor}}\\
          {\hit@put@title{\hit@cdatetitle}}
          & \underline{\makebox[\subject@length]{\hit@cdate}}
        }
      \end{tabular} \renewcommand{\arraystretch}{1}
      \end{center}
    }`
