### ISSUE TITLE
引用信息显示的不是数字，而是问号？

### ISSUE THREAD

**Issue by hiDaDeng** [hithesis/hithesis#204]
【环境】Mac、TinyTex、VSCode， 测试过可以正常编译中文内容。

【操作】
正文中使用 \cite{} 引用文献， 且 在reference.bib中有对应引用文献信息。 编译方法 xelatex -> bibtex ->xelatex*2

【问题】
引用信息显示的不是数字，而是问号？

**Comment by hiDaDeng** [comment]
【报错信息】This is XeTeX, Version 3.141592653-2.6-0.999994 (TeX Live 2022) (preloaded format=xelatex)

\write18 enabled.

entering extended mode

(./thesis.tex

LaTeX2e <2022-11-01> patch level 1

L3 programming layer <2023-02-22> (./hithesisbook.cls

Document Class: hithesisbook 2023/04/16 v3.1c Harbin Institute of Technology Thesis Template

(/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/kvoptions/kvoptions.sty (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/graphics/keyval.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/generic/ltxcmds/ltxcmds.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/kvsetkeys/kvsetkeys.sty)) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/base/ifthen.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/ctex/ctexbook.cls (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/ctex/config/ctexbackend.cfg) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/l3kernel/expl3.sty (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/l3backend/l3backendxetex.def))

Document Class: ctexbook 2022/07/14 v2.5.10 Chinese adapter for class book (CTEX)

(/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/ctex/ctexhook.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/ctex/ctexpatch.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/base/fix-cm.sty (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/base/ts1enc.def)) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/ctex/config/ctexopts.cfg) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/base/book.cls

Document Class: book 2022/07/02 v1.4n Standard LaTeX document class

(/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/base/bk12.clo)) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/ctex/engine/ctex-enginexetex.def (/Users/deng/Library/TinyTeX/texmf-dist/tex/xelatex/xecjk/xeCJK.sty (/Users/deng/Library/TinyTeX/texmf- dist/tex/latex/l3packages/xtemplate/xtemplate.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/fontspec/fontspec.sty (/Users/deng/Library/TinyTeX/texmfdist/tex/latex/l3packages/xparse/xparse.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/fontspec/fontspec-xetex.sty (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/base/fontenc.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/fontspec/fontspec.cfg))) (/Users/deng/Library/TinyTeX/texmf-dist/tex/xelatex/xecjk/xeCJK.cfg))) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/zhnumber/zhnumber.sty (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/zhnumber/zhnumberutf8.cfg)) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/ctex/scheme/ctexscheme-plain-book.def) (/Users/deng/Library/TinyTeX/texmfdist/tex/latex/ctex/ctex-cs4size.clo) (/Users/deng/Library/TinyTeX/texmfdist/tex/latex/ctex/fontset/ctex-fontset-fandol.def

Package fontspec Warning: Font "FandolSong-Regular" does not contain requested

(fontspec)

Script "CJK".

)) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/ctex/config/ctex.cfg) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/etoolbox/etoolbox.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/generic/iftex/ifxetex.sty (/Users/deng/Library/TinyTeX/texmf-dist/tex/generic/iftex/iftex.sty)) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/amsmath/amsmath.sty

For additional information on amsmath, use the `?' option.

(/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/amsmath/amstext.sty (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/amsmath/amsgen.sty)) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/amsmath/amsbsy.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/amsmath/amsopn.sty)) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/ntheorem/ntheorem.sty

Style `ntheorem', Version 1.33 <2011/08/15>

) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/amsfonts/amssymb.sty (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/amsfonts/amsfonts.sty)) (/Users/deng/Library/TinyTeX/texmfdist/tex/latex/newtx/TeXGyreTermesX.fontspec) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/newtx/newtxmath.sty `newtxmath' v1.71, 2022/01/16 Math macros based originally on txfonts (msharpe) (/Users/deng/Library/TinyTeX/texmf-dist/tex/generic/iftex/ifluatex.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/xkeyval/xkeyval.sty (/Users/deng/Library/TinyTeX/texmf-dist/tex/generic/xkeyval/xkeyval.tex (/Users/deng/Library/TinyTeX/texmf-dist/tex/generic/xkeyval/xkvutils.tex))) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/oberdiek/centernot.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/generic/kastrup/binhex.tex)

amsthm NOT loaded

) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/graphics/graphicx.sty (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/graphics/graphics.sty (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/graphics/trig.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/graphics-cfg/graphics.cfg) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/graphics-def/xetex.def))) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/pdfpages/pdfpages.sty (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/tools/calc.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/eso-pic/eso-pic.sty (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/xcolor/xcolor.sty (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/graphics-cfg/color.cfg) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/graphics/mathcolor.ltx))) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/pdfpages/ppxetex.def)) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/enumitem/enumitem.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/environ/environ.sty (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/trimspaces/trimspaces.sty)) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/footmisc/footmisc.sty (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/bigfoot/perpage.sty)) (/Users/deng/Library/TinyTeX/texmf-dist/tex/xelatex/xecjk/xeCJKfntef.sty (/Users/deng/Library/TinyTeX/texmf-dist/tex/generic/ulem/ulem.sty)) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/tools/longtable.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/booktabs/booktabs.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/hyperref/hyperref.sty (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pdftexcmds/pdftexcmds.sty (/Users/deng/Library/TinyTeX/texmf-dist/tex/generic/infwarerr/infwarerr.sty)) (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/kvdefinekeys/kvdefinekeys.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/generic/pdfescape/pdfescape.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/hycolor/hycolor.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/letltxmacro/letltxmacro.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/auxhook/auxhook.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/hyperref/nameref.sty (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/refcount/refcount.sty) (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/gettitlestring/gettitlestring.sty)) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/hyperref/pd1enc.def) (/Users/deng/Library/TinyTeX/texmf-dist/tex/generic/intcalc/intcalc.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/generic/etexcmds/etexcmds.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/hyperref/puenc.def) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/url/url.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/generic/bitset/bitset.sty (/Users/deng/Library/TinyTeX/texmf-dist/tex/generic/bigintcalc/bigintcalc.sty)) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/base/atbegshi-ltx.sty)) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/hyperref/hxetex.def (/Users/deng/Library/TinyTeX/texmf-dist/tex/generic/stringenc/stringenc.sty) (/Users/deng/Library/TinyTeX/texmfdist/tex/latex/rerunfilecheck/rerunfilecheck.sty (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/base/atveryend-ltx.sty) (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/uniquecounter/uniquecounter.sty))) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/gbt7714/gbt7714.sty (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/natbib/natbib.sty)) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/geometry/geometry.sty (/Users/deng/Library/TinyTeX/texmf-dist/tex/generic/iftex/ifvtex.sty)) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/fancyhdr/fancyhdr.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/tools/tabularx.sty (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/tools/array.sty)) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/varwidth/varwidth.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/changepage/changepage.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/tools/multicol.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/placeins/placeins.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/base/flafter.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/multirow/multirow.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/subfigure/subfigure.sty

************

* Local config file subfigure.cfg used *

************ (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/subfigure/subfigure.cfg)) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/ccaption/ccaption.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/splitindex/splitidx.sty)

Writing index file thesis.idx

Using splitted index at thesis.idx

(/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/glossaries/base/glossaries.sty (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/mfirstuc/mfirstuc.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/xfor/xfor.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/datatool/datatool-base.sty (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/substr/substr.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/datatool/datatool-fp.sty (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/fp/fp.sty `Fixed Point Package', Version 0.8, April 2, 1995 (C) Michael Mehlich (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/fp/defpattern.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/fp/fp-basic.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/fp/fp-addons.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/fp/fp-snap.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/fp/fp-exp.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/fp/fp-trigo.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/fp/fp-pas.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/fp/fp-random.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/fp/fp-eqn.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/fp/fp-upn.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/fp/fp-eval.sty)))) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/glossaries/styles/glossaryhypernav.sty) (/Users/deng/Library/TinyTeX/texmfdist/tex/latex/glossaries/styles/glossary-list.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/glossaries/styles/glossarylong.sty) (/Users/deng/Library/TinyTeX/texmfdist/tex/latex/glossaries/styles/glossary-super.sty (/Users/deng/Library/TinyTeX/texmfdist/tex/latex/supertabular/supertabular.sty)) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/glossaries/styles/glossarytree.sty))) (./hithesisbook.cfg) (./hithesis.sty (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/siunitx/siunitx.sty (/Users/deng/Library/TinyTeX/texmfdist/tex/latex/translations/translations.sty)) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/tools/bm.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/jknapltx/mathrsfs.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/graphics/rotating.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/algorithm2e/algorithm2e.sty (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/ifoddpage/ifoddpage.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/tools/xspace.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/relsize/relsize.sty)) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/listings/listings.sty (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/listings/lstmisc.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/listings/listings.cfg)) (/Users/deng/Library/TinyTeX/texmf-dist/tex/xelatex/xecjk/xeCJK-listings.sty) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/pgf/frontendlayer/tikz.sty (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/pgf/basiclayer/pgf.sty (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/pgf/utilities/pgfrcs.sty (/Users/deng/Library/TinyTeX/texmf-dist/tex/generic/pgf/utilities/pgfutilcommon.tex) (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/utilities/pgfutil-latex.def) (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/utilities/pgfrcs.code.tex (/Users/deng/Library/TinyTeX/texmf-dist/tex/generic/pgf/pgf.revision.tex))) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/pgf/basiclayer/pgfcore.sty (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/pgf/systemlayer/pgfsys.sty (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/systemlayer/pgfsys.code.tex (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/utilities/pgfkeys.code.tex (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/utilities/pgfkeyslibraryfiltered.code.tex)) (/Users/deng/Library/TinyTeX/texmf-dist/tex/generic/pgf/systemlayer/pgf.cfg) (/Users/deng/Library/TinyTeX/texmf-dist/tex/generic/pgf/systemlayer/pgfsysxetex.def (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/systemlayer/pgfsys-dvipdfmx.def (/Users/deng/Library/TinyTeX/texmf-dist/tex/generic/pgf/systemlayer/pgfsyscommon-pdf.def)))) (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/systemlayer/pgfsyssoftpath.code.tex) (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/systemlayer/pgfsysprotocol.code.tex)) (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/basiclayer/pgfcore.code.tex (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/math/pgfmath.code.tex (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/math/pgfmathutil.code.tex) (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/math/pgfmathparser.code.tex) (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/math/pgfmathfunctions.code.tex) (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/math/pgfmathfunctions.basic.code.tex) (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/math/pgfmathfunctions.trigonometric.code.tex) (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/math/pgfmathfunctions.random.code.tex) (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/math/pgfmathfunctions.comparison.code.tex) (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/math/pgfmathfunctions.base.code.tex) (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/math/pgfmathfunctions.round.code.tex) (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/math/pgfmathfunctions.misc.code.tex) (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/math/pgfmathfunctions.integerarithmetics.code.tex) (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/math/pgfmathcalc.code.tex) (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/math/pgfmathfloat.code.tex)) (/Users/deng/Library/TinyTeX/texmf-dist/tex/generic/pgf/math/pgfint.code.tex) (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/basiclayer/pgfcorepoints.code.tex) (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/basiclayer/pgfcorepathconstruct.code.tex) (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/basiclayer/pgfcorepathusage.code.tex) (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/basiclayer/pgfcorescopes.code.tex) (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/basiclayer/pgfcoregraphicstate.code.tex) (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/basiclayer/pgfcoretransformations.code.tex) (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/basiclayer/pgfcorequick.code.tex) (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/basiclayer/pgfcoreobjects.code.tex) (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/basiclayer/pgfcorepathprocessing.code.tex) (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/basiclayer/pgfcorearrows.code.tex) (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/basiclayer/pgfcoreshade.code.tex) (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/basiclayer/pgfcoreimage.code.tex) (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/basiclayer/pgfcoreexternal.code.tex) (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/basiclayer/pgfcorelayers.code.tex) (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/basiclayer/pgfcoretransparency.code.tex) (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/basiclayer/pgfcorepatterns.code.tex) (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/basiclayer/pgfcorerdf.code.tex))) (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/modules/pgfmoduleshapes.code.tex) (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/modules/pgfmoduleplot.code.tex) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/pgf/compatibility/pgfcompversion-0-65.sty) (/Users/deng/Library/TinyTeX/texmfdist/tex/latex/pgf/compatibility/pgfcomp-version-1-18.sty)) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/pgf/utilities/pgffor.sty (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/pgf/utilities/pgfkeys.sty (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/utilities/pgfkeys.code.tex)) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/pgf/math/pgfmath.sty (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/math/pgfmath.code.tex)) (/Users/deng/Library/TinyTeX/texmf- dist/tex/generic/pgf/utilities/pgffor.code.tex)) (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/frontendlayer/tikz/tikz.code.tex (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/libraries/pgflibraryplothandlers.code.tex) (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/modules/pgfmodulematrix.code.tex) (/Users/deng/Library/TinyTeX/texmfdist/tex/generic/pgf/frontendlayer/tikz/libraries/tikzlibrarytopaths.code.tex))))

No file thesis.aux.

(/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/newtx/omlntxmi.fd) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/newtx/untxexa.fd) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/newtx/lmsntxsy.fd) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/newtx/lmxntxexx.fd) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/pdflscape/pdflscape.sty (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/pdflscape/pdflscapenometadata.sty (/Users/deng/Library/TinyTeX/texmfdist/tex/latex/graphics/lscape.sty)))

Package hyperref Warning: Rerun to get /PageLabels entry.

geometry driver: auto-detecting geometry detected driver: xetex

(/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/translations/translationsbasic-dictionary-english.trsl) (./front/cover.tex)

Package fontspec Warning: Font "FandolSong-Regular" does not contain requested

(fontspec)

Script "CJK".

Package fontspec Warning: Font "FandolHei-Regular" does not contain requested

(fontspec)

Script "CJK".

Package fontspec Warning: Font "FandolKai-Regular" does not contain requested

(fontspec)

Script "CJK". [1] [2] (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/newtx/ot1ntxtlf.fd) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/amsfonts/umsa.fd) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/amsfonts/umsb.fd) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/newtx/untxmia.fd) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/newtx/untxsym.fd) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/newtx/untxsyc.fd) (/Users/deng/Library/TinyTeX/texmf-dist/tex/latex/jknapltx/ursfs.fd) LaTeX Font Warning: Font shape `U/rsfs/m/n' in size <10.53937> not available (Font) size <10.95> substituted on input line 107.

LaTeX Font Warning: Font shape `U/rsfs/m/n' in size <7.52812> not available (Font) size <8> substituted on input line 107.

[3] [4] [5] [6] [1] (./front/denotation.tex [2]) [3] No file thesis.toc.

[4]

No file thesis.toe.

[5] [6] (./body/regu.tex 第1章

[1] [2] [3] [4]

Missing character: There is no □ (U+25A1) in font [TeXGyreTermesXRegular.otf]/OT:script=latn;language=dflt;mapping=tex-text;! Missing character: There is no □ (U+25A1) in font [TeXGyreTermesXRegular.otf]/OT:script=latn;language=dflt;mapping=tex-text;!

[5]

Package natbib Warning: Citation `cnproceed' on page 6 undefined on input line

192.

Package natbib Warning: Citation `cnarticle' on page 6 undefined on input line 195. Package natbib Warning: Citation `cnproceed' on page 6 undefined on input line

195. Package fontspec Warning: Font "FandolFang-Regular" does not contain requested (fontspec) Script "CJK".

Package natbib Warning: Citation `cnarticle' on page 6 undefined on input line 196. Package natbib Warning: Citation `cnproceed' on page 6 undefined on input line

196.

Package natbib Warning: Citation `cnarticle' on page 6 undefined on input line 199. Package natbib Warning: Citation `cnarticle' on page 6 undefined on input line 200. Package natbib Warning: Citation `hithesis2017' on page 6 undefined on input line

202.

[6] [7] [8] [9] [10]

Underfull \hbox (badness 10000) in paragraph at lines 352--353 []\TU/FandolSong-Regular(0)/m/n/12.045 为 了 便 于 学 位 论 ⽂ 的 管 理，| 建 议 参 照 |《图 书 和 其 它 出 版 物 的 书 脊 规 ) [11] (./body/introduction.tex 第2章 LaTeX Font Warning: Font shape `OMS/TeXGyreTermesX(0)/m/n' undefined (Font) using `OMS/cmsy/m/n' instead on input line 6.

[12]

Package natbib Warning: Citation `cnproceed' on page 13 undefined on input line

43.

Package natbib Warning: Citation `cnarticle' on page 13 undefined on input line 46. Package natbib Warning: Citation `cnproceed' on page 13 undefined on input line

46.

Package natbib Warning: Citation `cnarticle' on page 13 undefined on input line 47. Package natbib Warning: Citation `cnproceed' on page 13 undefined on input line

47. Package natbib Warning: Citation `cnarticle' on page 13 undefined on input line 50. Package natbib Warning: Citation `cnarticle' on page 13 undefined on input line 51. Package natbib Warning: Citation `hithesis2017' on page 13 undefined on input line

53.

Package natbib Warning: Citation `cnproceed' on page 13 undefined on input line

56.

[13] [14] [15] [16]

LaTeX Warning: !h' float specifier changed to!ht'. LaTeX Warning: !h' float specifier changed to!ht'.

[17] [18] [19] [20]dyld[74721]: Library not loaded: /opt/homebrew/opt/libtiff/lib/libtiff.5.dylib Referenced from: <39C98603-8BD8-3AC1-BF93-6BBF992670E7> /opt/homebrew/Cellar/ghostscript/10.0.0/bin/gs Reason: tried: '/opt/homebrew/opt/libtiff/lib/libtiff.5.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/libtiff/lib/libtiff.5.dy lib' (no such file), '/opt/homebrew/opt/libtiff/lib/libtiff.5.dylib' (no such file), '/usr/local/lib/libtiff.5.dylib' (no such file), '/usr/lib/libtiff.5.dylib' (no such file, not in dyld cache), '/opt/homebrew/Cellar/libtiff/4.6.0/lib/libtiff.5.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/Cellar/libtiff/4.6.0/lib/li btiff.5.dylib' (no such file), '/opt/homebrew/Cellar/libtiff/4.6.0/lib/libtiff.5.dylib' (no such file), '/usr/local/lib/libtiff.5.dylib' (no such file), '/usr/lib/libtiff.5.dylib' (no such file, not in dyld cache) xdvipdfmx:fatal: Image inclusion failed for "figures//golfer.eps" (page=1).

No output PDF file written.

LaTeX Warning: Reference `drawtool' on page 21 undefined on input line 274. Missing character: There is no ; ("3B) in font nullfont!

Missing character: There is no ; ("3B) in font nullfont!

Missing character: There is no ; ("3B) in font nullfont! Missing character: There is no ; ("3B) in font nullfont! Missing character: There is no ; ("3B) in font nullfont! Missing character: There is no ; ("3B) in font nullfont! Missing character: There is no ; ("3B) in font nullfont! Missing character: There is no ; ("3B) in font nullfont! Missing character: There is no ; ("3B) in font nullfont! Missing character: There is no ; ("3B) in font nullfont! Missing character: There is no ; ("3B) in font nullfont! Missing character: There is no ; ("3B) in font nullfont! Missing character: There is no ; ("3B) in font nullfont! Missing character: There is no ; ("3B) in font nullfont! Missing character: There is no ; ("3B) in font nullfont! Missing character: There is no ; ("3B) in font nullfont! Missing character: There is no ; ("3B) in font nullfont! Missing character: There is no ; ("3B) in font nullfont! Missing character: There is no ; ("3B) in font nullfont! Missing character: There is no ; ("3B) in font nullfont! Missing character: There is no ; ("3B) in font nullfont! Missing character: There is no ; ("3B) in font nullfont! Missing character: There is no ; ("3B) in font nullfont! Missing character: There is no ; ("3B) in font nullfont! Missing character: There is no ; ("3B) in font nullfont! Missing character: There is no ; ("3B) in font nullfont! Missing character: There is no ; ("3B) in font nullfont! Missing character: There is no ; ("3B) in font nullfont! Missing character: There is no ; ("3B) in font nullfont!

Missing character: There is no ; ("3B) in font nullfont!

LaTeX Warning: Reference `tumor' on page 21 undefined on input line 321. LaTeX Warning: Reference `table1' on page 21 undefined on input line 342. [21

**Comment by hiDaDeng** [comment]
问题已解决，编译环境有删除中间文件的设置， 停用这个功能后， 能编译出pdf。

**Comment by syvshc** [comment]
这个需要看一下 `thesis.bbl` 文件是否正常生成, 以及此文件中是否有你引用的文献信息
