### ISSUE TITLE
英文目录，章节会悬挂0.5em

### ISSUE THREAD

**Issue by baoyu2020** [hithesis/hithesis#209]
## 描述bug类型

- 校区：哈尔滨

- 学位：博

- 论文类型：毕业论文

- LaTeX 发行版）：TeXLive 2023

- 模板版本：v3.1c

## 描述bug具体信息

- 请给出完整的示例文件：

```latex

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\documentclass[fontset=windows,type=doctor,campus=harbin, tocblank=false, chapterhang=false]{hithesisbook}

\usepackage{hithesis}

\graphicspath{{figures/}}

\begin{document}
\frontmatter
\input{front/cover} % 封面
\makecover
% \input{front/denotation}%物理量名称表,符合规范为主，有要求添加
\tableofcontents %目录
% \listoffigures
% \listoftables
\mainmatter
\include{body/regu}
\include{body/introduction}
\backmatter
\include{back/conclusion}   % 结论
\bibliographystyle{gbt7714-numerical}
\bibliography{reference} % 参考文献
\begin{appendix}%附录
\input{back/appA.tex}
\end{appendix}
\include{back/publications}    % 所发文章
\include{back/ceindex}    % 索引, 根据自己的情况添加或者不添加，选择自动添加或者手工添加。
\authorization %授权
%\authorization[scan.pdf] %添加扫描页的命令，与上互斥
\include{back/acknowledgements} %致谢
\include{back/resume}          % 博士学位论文有个人简介

```

或将整个 `hitbook/chinese`, `reports` 或 `reportplus` 压缩后上传 `.zip` 文件

- 使用什么编译方式（`xelatex`/`latexmk`/`make thesis`）：xelatex
- 编译报错 or 编译结果与预期不符：编译结果与预期不符

- 如果有编译报错，可以将报错信息截图粘贴到下面：

- 如果编译结果与预期不符：
  - 预期结果的截图
![image](https://github.com/hithesis/hithesis/assets/70013796/e7084bfc-da7c-4eeb-9c61-8c50b6f0137f)

  - 编译后的效果截图
![image](https://github.com/hithesis/hithesis/assets/70013796/2dc28027-b8bb-41a7-955d-a2c6e01baaec)

  如上图，英文的目录，Chapter和Appendix 都会悬挂0.5em。生成的中文目录不会出现这个问题。

- 将编译后产生的 `.log` 文件上传到这里。

**Comment by syvshc** [comment]
在 `hithesisbook.cls` 中搜索
```tex
  {% if \chapter
    \IfNoValueTF{#2}%
    {\hit@chapter{#3}}%
    {\hit@chapter[#2]{#3}}%
    \IfValueT{#4}{%
      \addcontentsline{toe}{chapter}
        {
          \texorpdfstring
            {\bfseries\relax \hit@engtoc@chapapp \thechapter\hspace{0.5em}\ignorespaces #4}
            {\hit@engtoc@chapapp \thechapter\hspace{0.5em}\ignorespaces #4}
        }
    }
  }
```
在
···tex
    \IfValueT{#4}{%
      \addcontentsline{toe}{chapter}
        {%                   <-这里加一个 %
          \texorpdfstring
            {\bfseries\relax \hit@engtoc@chapapp \thechapter\hspace{0.5em}\ignorespaces #4}
            {\hit@engtoc@chapapp \thechapter\hspace{0.5em}\ignorespaces #4}
        }
```
修复后的 dev 分支推送后会将这个问题打上 `fixed in dev` 的标签。
