### ISSUE TITLE
\subequations{} will copy current chapter and enforce to create a new chapter 

### ISSUE THREAD

**Issue by ruanqc** [hithesis/hithesis#217]
## 描述bug类型

- 校区（哈尔滨/威海/深圳？）：深圳

- 学位（本/硕/博？）：博

- 论文类型（毕业论文/开题/中期/博后/English Version？）：English Version

- LaTeX 发行版（TeXLive 20xx/MikTeX/**本模板不支持CTeX套装**）：

- 模板版本（在 `hithesis***.cls` 中的 `\ProvidesClass` 命令中的 `3.x.xx` 或 `3.xx` 即为版本号）：hithesis-v3.1d-env /  hithesis-v3.1c-env

## 描述bug具体信息
编译英文博士学位论文，当含有\subequations{} 时会强行复制生成新的章节当前章节.
eg: 写ch2， 在该章节编译含\subequations{} 部分后，编译结果会强行增加一章，显示结果示例如下，

"ch2 xxxxxx  
\subequations{}  
ch3 xxxxxx 
\subequations{} "

- 请给出完整的示例文件：

```latex
% 将 thesis.tex/report.tex 中的内容完整地放在这里
% tex in cd/hithesis-v3.1d-env\hitbook\english\body
% !Mode:: "TeX:UTF-8"
\chapter{test_subeq}
\section{test}

\begin{subequations}
	\label{sdot}
	\begin{align}
		%%% source edge
		\dot{\rho}_{S_{e}}^\alpha = &   
		\dfrac{C_e}{b^\alpha} \; \left[ K_e \, \sqrt{
			\sum_{\beta=1}^{N}
			\rho^\beta} \, - \; 2 \, d_e \; \rho_{S_{e}}^\alpha\right]  \; \left| \dot{\gamma}^\alpha\right| \,, \tag{70a}     \label{rhoedot}\\
		%%% source screw
		\dot{\rho}_{S_{s}}^\alpha = &   
		\dfrac{C_s}{b^\alpha} \; \left[ K_s \, \sqrt{
			\sum_{\beta=1}^{N} 
			\rho^\beta} \, - \; \rho_{S_{s}}^\alpha \;
		\left( 
		\pi \, {d_s}^2 \, K_s \,   \sqrt{\sum_{\beta=1}^{N}\rho^\beta} \,+ \, 2 \, d_s\right) \; 
		\right]  \left| \dot{\gamma}^\alpha\right|.
		\tag{70b}  \label{rhosdot}
	\end{align}
\end{subequations}
```

或将整个 `hitbook/chinese`, `reports` 或 `reportplus` 压缩后上传 `.zip` 文件

- 使用什么编译方式（`xelatex`/`latexmk`/`make thesis`）：
- 编译报错 or 编译结果与预期不符：

- 如果有编译报错，可以将报错信息截图粘贴到下面：

- 如果编译结果与预期不符：
  - 预期结果的截图
![2331](https://github.com/hithesis/hithesis/assets/88821046/08eb5142-0f08-4f7b-8406-82c4b7f15e71)

  - 编译后的效果截图
![2332](https://github.com/hithesis/hithesis/assets/88821046/3687706c-7f92-4887-949e-f680545ff6f2)

- 将编译后产生的 `.log` 文件上传到这里。
-
[thesis.log](https://github.com/hithesis/hithesis/files/14833916/thesis.log)

**Comment by syvshc** [comment]
我问一下哈, 英文版有给公式写 caption 的需求吗?

**Comment by ruanqc** [comment]
> 我问一下哈, 英文版有给公式写 caption 的需求吗?

一般图表会加，没有给公式加过caption。其实拆开分两个equ也可以，只是刚好编译遇到了这种神奇的bug😂😂

**Comment by syvshc** [comment]
> > 我问一下哈, 英文版有给公式写 caption 的需求吗?
> 
> 一般图表会加，没有给公式加过caption。其实拆开分两个equ也可以，只是刚好编译遇到了这种神奇的bug😂😂

这个问题和 #203 是一样的原因, 重定义了 `\tag` 相关的命令, 但是没考虑到 hyperref 中的情况……这部分是初代目写的, 我没看出来有什么作用……删掉 `hithesisbook.cls` 中的
```latex
\def\make@df@tag{\@ifstar\hit@make@df@tag@@\make@df@tag@@@}
\def\hit@make@df@tag@@#1{\gdef\df@tag{\hit@maketag{#1}\def\@currentlabel{#1}}}
\iffalse
\ifhit@bachelor
  \def\hit@maketag#1{\maketag@@@{%
    (\ignorespaces\text{\equationname\hskip0.5em}#1\unskip\@@italiccorr)}}
  \def\tagform@#1{\maketag@@@{%
    (\ignorespaces\text{\equationname\hskip0.5em}#1\unskip\@@italiccorr)\equcaption{#1}}}
\fi
\fi
\def\hit@maketag#1{\maketag@@@{(\ignorespaces #1\unskip\@@italiccorr)}}
\def\tagform@#1{\maketag@@@{(\ignorespaces #1\unskip\@@italiccorr)\equcaption{#1}}}
\renewcommand{\eqref}[1]{\textup{(\ref{#1})}}
```
后看看有什么不妥的地方.

**Comment by ruanqc** [comment]
> > > 我问一下哈, 英文版有给公式写 caption 的需求吗?
> > 
> > 
> > 一般图表会加，没有给公式加过caption。其实拆开分两个equ也可以，只是刚好编译遇到了这种神奇的bug😂😂
> 
> 这个问题和 #203 是一样的原因, 重定义了 `\tag` 相关的命令, 但是没考虑到 hyperref 中的情况……这部分是初代目写的, 我没看出来有什么作用……删掉 `hithesisbook.cls` 中的
> 
> ```
> \def\make@df@tag{\@ifstar\hit@make@df@tag@@\make@df@tag@@@}
> \def\hit@make@df@tag@@#1{\gdef\df@tag{\hit@maketag{#1}\def\@currentlabel{#1}}}
> \iffalse
> \ifhit@bachelor
>   \def\hit@maketag#1{\maketag@@@{%
>     (\ignorespaces\text{\equationname\hskip0.5em}#1\unskip\@@italiccorr)}}
>   \def\tagform@#1{\maketag@@@{%
>     (\ignorespaces\text{\equationname\hskip0.5em}#1\unskip\@@italiccorr)\equcaption{#1}}}
> \fi
> \fi
> \def\hit@maketag#1{\maketag@@@{(\ignorespaces #1\unskip\@@italiccorr)}}
> \def\tagform@#1{\maketag@@@{(\ignorespaces #1\unskip\@@italiccorr)\equcaption{#1}}}
> \renewcommand{\eqref}[1]{\textup{(\ref{#1})}}
> ```
> 
> 后看看有什么不妥的地方.

多谢。确实可能是tag重编号和模板某些规范定义冲突导致的，这两天去试试不加tag会不会有区别。因为在elsvier模板编译没啥问题就直接拷过来了学校模板了

**Comment by syvshc** [comment]
那个tag我也没看懂改了什么东西……先这么用着吧

**Comment by ruanqc** [comment]
> 那个tag我也没看懂改了什么东西……先这么用着吧

comment 掉\tag后subequation也能正常编译了。进一步测试了下差不多搞懂了，这个模板应该是不允许加tag的（加了也不起作用）
1. 在\equation{} 里加\tag 会阻断后续内容编译（没有tag后续的全部内容），
2. 在 \eqnarray{}里加\tag 不影响编译， 3. 如帖子所述情况。

**Comment by syvshc** [comment]
```latex
\documentclass[fontset=fandol,type=doctor,campus=shenzhen,language=english]{hithesisbook}
\usepackage{hithesis}
\usepackage{lipsum}
\graphicspath{{figures/}}
\begin{document}

\lipsum[1]
\begin{equation}
  \int_{0}^{1} x^2 \, dx \tag{one}\label{eq:1}
\end{equation}
\lipsum[2]
\begin{align}
  \int_{0}^{1} x^2 \, dx \tag{two}\label{eq:2}\\
  \int_{0}^{1} x^2 \, dx \tag{three}\label{eq:3}
\end{align}
\lipsum[3]

HERE IS \eqref{eq:1} and \eqref{eq:2} and \eqref{eq:3}
\end{document}
```
两次 xelatex 后输出正常
![image](https://github.com/hithesis/hithesis/assets/38098591/f24fe6fb-adce-48c2-8257-b6d23b64279f)

**Comment by ruanqc** [comment]
> ```
> \documentclass[fontset=fandol,type=doctor,campus=shenzhen,language=english]{hithesisbook}
> \usepackage{hithesis}
> \usepackage{lipsum}
> \graphicspath{{figures/}}
> \begin{document}
> 
> \lipsum[1]
> \begin{equation}
>   \int_{0}^{1} x^2 \, dx \tag{one}\label{eq:1}
> \end{equation}
> \lipsum[2]
> \begin{align}
>   \int_{0}^{1} x^2 \, dx \tag{two}\label{eq:2}\\
>   \int_{0}^{1} x^2 \, dx \tag{three}\label{eq:3}
> \end{align}
> \lipsum[3]
> 
> HERE IS \eqref{eq:1} and \eqref{eq:2} and \eqref{eq:3}
> \end{document}
> ```
> 
> 两次 xelatex 后输出正常 ![image](https://private-user-images.githubusercontent.com/38098591/320257168-f24fe6fb-adce-48c2-8257-b6d23b64279f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NzE1MzAsIm5iZiI6MTcxMjQ3MTIzMCwicGF0aCI6Ii8zODA5ODU5MS8zMjAyNTcxNjgtZjI0ZmU2ZmItYWRjZS00OGMyLTgyNTctYjZkMjNiNjQyNzlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDA2MjcxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmNWZlM2I1ZjVmMjU0MWQ3MmRkNzNjOTM2ZGZjNmU3YWY2NjEwNDBlNWFkZGU4ODQ2ODM1OGMyMzc5NzlkMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KUZdHwJdutRXpGPeUPyoS1l_zXwiZSxkMfNyZMtNrTg)

神奇的地球~
