### ISSUE TITLE
大标题在段前段后均出现“28.34646bp” 和 “28.74646bp”

### ISSUE THREAD

**Issue by ruanqc** [hithesis/hithesis#221]
## 描述bug类型

- 校区（哈尔滨/威海/深圳？）：深圳

- 学位（本/硕/博？）：博

- 论文类型（毕业论文/开题/中期/博后/English Version？）：English Version

- LaTeX 发行版（TeXLive 20xx/MikTeX/**本模板不支持CTeX套装**）：TeXLive 2024

- 模板版本（在 `hithesis***.cls` 中的 `\ProvidesClass` 命令中的 `3.x.xx` 或 `3.xx` 即为版本号）：v3.1d

## 描述bug具体信息

- 请给出完整的示例文件：

```latex
% 将 thesis.tex/report.tex 中的内容完整地放在这里
% !Mode:: "TeX:UTF-8"
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%          ,
%      /\^/`\
%     | \/   |                CONGRATULATIONS!
%     | |    |             SPRING IS IN THE AIR!
%     \ \    /                                                _ _
%      '\\//'                                               _{ ' }_
%        ||                     hithesis v3                { `.!.` }
%        ||                                                ',_/Y\_,'
%        ||  ,                   dustincys                   {_,_}
%    |\  ||  |\          Email: yanshuoc@gmail.com             |
%    | | ||  | |            https://yanshuo.site             (\|  /)
%    | | || / /                                               \| //
%    \ \||/ /       https://github.com/dustincys/hithesis      |//
%      `\\//`   \\   \./    \\ /     //    \\./   \\   //   \\ |/ /
%     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\documentclass[fontset=fandol,type=doctor,campus=shenzhen,language=english]{hithesisbook}
% No space between options
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Mandatory option
% type=doctor|master|bachelor|postdoc
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Optional option (with default value)
% campus=shenzhen|weihai|harbin
%   Default:harbin
% glue=true|false
%   Line spacing: true means [3,4]mm, false means 3mm。
% tocfour=true|false
%   TOC level four or three
% fontset=windows|mac|ubuntu|fandol|adobe|founder
%   Normally, TeX could detect your OS font automatically. If not, explicitly
%   set your OS here, or, use open source font set
% newgeometry=one|two
%   Geometry of text area in the page. `two' is good for now.
% openright=true|false
%   Force the Chapter page number to be even or not.
% library=true|false
%   Set this option will remove all blank page in your thesis, Library preferred.
% newtxmath=true|false
%   Math font used in the thesis
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\usepackage{hithesis}
\graphicspath{figures/}
\begin{document}

\frontmatter
\input{front/cover}
%\makecover
\include{front/acknowledgements}
\tableofcontents

\mainmatter
\include{body/1_Introduction}
\include{body/2_CDF_Framework}
\include{body/3_Application_1D2DPU}
\include{body/4_Application_2DBVP}
\include{body/5_Application_2DHIclude}

\backmatter
\include{back/conclusion}
\bibliographystyle{hithesis}
\bibliography{reference}


\include{back/appA}


\include{back/publications}
\authorization
%\authorization[scanversion.pdf]

\include{back/resume}


\end{document}

% Local Variables:
% TeX-engine: xetex
% End:

```

或将整个 `hitbook/chinese`, `reports` 或 `reportplus` 压缩后上传 `.zip` 文件

- 使用什么编译方式（`xelatex`/`latexmk`/`make thesis`）：latexmk
- 编译报错 or 编译结果与预期不符：
大标题（contents/chaper/acknowledgements等）均在段前和段后分别出现28.34646bp 和 28.74646bp
- 如果有编译报错，可以将报错信息截图粘贴到下面：

- 如果编译结果与预期不符：
  - 预期结果的截图

  - 编译后的效果截图
![image](https://github.com/hithesis/hithesis/assets/88821046/a1533328-2b0f-413a-8591-f27b6badf21c)
![image](https://github.com/hithesis/hithesis/assets/88821046/863a93b1-a956-429a-8138-3b37a7d771b0)
![image](https://github.com/hithesis/hithesis/assets/88821046/68deb565-8b04-4d45-9880-d0f7b90e394a)

- 将编译后产生的 `.log` 文件上传到这里。
[thesis.log](https://github.com/hithesis/hithesis/files/15245742/thesis.log)

**Comment by syvshc** [comment]
看了一下你的Log, 里面有很多的报错信息, 你可以尝试先编译示例模板, 看一下有没有错误, 再向其中添加内容

**Comment by ruanqc** [comment]
> 看了一下你的Log, 里面有很多的报错信息, 你可以尝试先编译示例模板, 看一下有没有错误, 再向其中添加内容

一样的呢， 示例文件我这边编译文件和结果如下

%thesis.tex----------------------------------------------------------------------------------begin---------------------
% !Mode:: "TeX:UTF-8"
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%          ,
%      /\^/`\
%     | \/   |                CONGRATULATIONS!
%     | |    |             SPRING IS IN THE AIR!
%     \ \    /                                                _ _
%      '\\//'                                               _{ ' }_
%        ||                     hithesis v3                { `.!.` }
%        ||                                                ',_/Y\_,'
%        ||  ,                   dustincys                   {_,_}
%    |\  ||  |\          Email: yanshuoc@gmail.com             |
%    | | ||  | |            https://yanshuo.site             (\|  /)
%    | | || / /                                               \| //
%    \ \||/ /       https://github.com/dustincys/hithesis      |//
%      `\\//`   \\   \./    \\ /     //    \\./   \\   //   \\ |/ /
%     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\documentclass[fontset=fandol,type=doctor,campus=shenzhen,language=english]{hithesisbook}
% No space between options
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Mandatory option
% type=doctor|master|bachelor|postdoc
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Optional option (with default value)
% campus=shenzhen|weihai|harbin
%   Default:harbin
% glue=true|false
%   Line spacing: true means [3,4]mm, false means 3mm。
% tocfour=true|false
%   TOC level four or three
% fontset=windows|mac|ubuntu|fandol|adobe|founder
%   Normally, TeX could detect your OS font automatically. If not, explicitly
%   set your OS here, or, use open source font set
% newgeometry=one|two
%   Geometry of text area in the page. `two' is good for now.
% openright=true|false
%   Force the Chapter page number to be even or not.
% library=true|false
%   Set this option will remove all blank page in your thesis, Library preferred.
% newtxmath=true|false
%   Math font used in the thesis
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
\usepackage{hithesis}
\graphicspath{{figures/}}
\begin{document}

\frontmatter
\input{front/cover}
\makecover
\include{front/acknowledgements}
\tableofcontents

\mainmatter
\include{body/eng_regu}

\backmatter
\include{back/conclusion}
\bibliographystyle{hithesis}
\bibliography{reference}
\include{back/publications}
\authorization
%\authorization[scanversion.pdf]
\end{document}

% Local Variables:
% TeX-engine: xetex
% End:
%----------------------------------------------------------------------------end------------------------

![image](https://github.com/hithesis/hithesis/assets/88821046/20487d94-a395-47ab-aff3-5c8f8418c508)
![image](https://github.com/hithesis/hithesis/assets/88821046/2dc00a5c-81b7-4fd9-86da-718ce11147a7)

**Comment by ruanqc** [comment]
> 你这个 3.1d 版本是什么时候下载的? 可以考虑从dev分支重新下载并生成模板看一下, 我记得处理过 `missing number` 的问题

Q群下载的2024-03-13 更新的版本

**Comment by syvshc** [comment]
> > 你这个 3.1d 版本是什么时候下载的? 可以考虑从dev分支重新下载并生成模板看一下, 我记得处理过 `missing number` 的问题
> 
> Q群下载的2024-03-13 更新的版本

#200 是 2024-3-22 解决的, 更新一下吧

**Comment by ruanqc** [comment]
> > > 你这个 3.1d 版本是什么时候下载的? 可以考虑从dev分支重新下载并生成模板看一下, 我记得处理过 `missing number` 的问题
> > 
> > 
> > Q群下载的2024-03-13 更新的版本
> 
> #200 是 2024-3-22 解决的, 更新一下吧

下载更新到#219 fix 的dev版本正常编译了，感谢~
