### ISSUE TITLE
\NewDocumentCommand{\authorization}的其中一个判断语句的\fi位置放错了应该

### ISSUE THREAD

**Issue by kuro26** [hithesis/hithesis#223]
## 描述bug类型
在包含`原创性申明`pdf文件时，对应中文标题会为空
hithesis.dtx文件中：
```\hit@declarename@bachelor\else\hit@authorization@ctitle\fi\fi}%```
改成：
```\hit@declarename@bachelor\fi\else\hit@authorization@ctitle\fi}%```

**Comment by syvshc** [comment]
在 dev 分支的  13953a4 已经修改过了
