### ISSUE TITLE
目录中摘要和第一章之间多一个空行

### ISSUE THREAD

**Issue by BG2CRY** [hithesis/hithesis#225]
**请不要主动关闭 issue，如果问题已经解决并推送到 [dev](https://github.com/hithesis/hithesis/tree/dev) 分支，该 issue 会被打上 `fixed in dev` 的标签，并在合并到 [master](https://github.com/hithesis/hithesis/tree/master) 分支后关闭。** 
## 基本信息

- 校区（哈尔滨/威海/深圳？）：哈尔滨

- 学位（本/硕/博？）：博士

- 论文类型（毕业论文/开题/中期/博后/English Version？）：毕业论文

- LaTeX 发行版（TeXLive 20xx/MikTeX/**本模板不支持CTeX套装**）：

- 模板版本（在 `hithesis***.cls` 中的 `\ProvidesClass` 命令中的 `3.x.xx` 或 `3.xx` 即为版本号）：[2021/05/17 v3.1a Harbin Institute of Technology Thesis Template]

## 描述模板不符合的具体信息

窝工在（规范/word模板中）第（xxx）行规定格式为：在2021年5月13日发布的“研究生学位论文书写范例（理工类）”模板中，目录中摘要宇第一章中间没有空行

如图：![QQ截图20240516155432](https://github.com/hithesis/hithesis/assets/32352748/b346c53e-3b88-412b-92d1-7c0b61d64d5f)

hithesis的格式中摘要和第一章中间有一行空行

如图：
![2](https://github.com/hithesis/hithesis/assets/32352748/9af0ef1e-b06d-4588-b3fc-1964443b5a90)

**Comment by syvshc** [comment]
为什么不看 `\documentclass` 下面的参数说明？
