### ISSUE TITLE
hithesisbook gbt7714-numerical 对bib文件中参考文献条目的要求是什么？

### ISSUE THREAD

**Issue by EagleLee0** [hithesis/hithesis#234]
## 基本信息

- 校区（哈尔滨/威海/深圳？）：哈尔滨

- 学位（本/硕/博？）：博

- 论文类型（毕业论文/开题/中期/博后/English Version？）：毕业论文

- LaTeX 发行版（TeXLive 20xx/MikTeX/**本模板不支持CTeX套装**）：TeXLive 2022

- 模板版本（在 `hithesis***.cls` 中的 `\ProvidesClass` 命令中的 `3.x.xx` 或 `3.xx` 即为版本号）：v3.1c

## 想实现的效果

latexmk编译方式，想知道\bibliographystyle{gbt7714-numerical}这一句的gbt7714-numerical要求bib文件有哪些属性？哪些必选，哪些可选，哪些通用？

比如bib文件包含如下条目
@phdthesis{GoelA05,
   author = {Goel, Anukul},
   title = {Robust control of supercavitating vehicles in the presence of dynamic and uncertain cavity},
   university = {University of Florida},
   year = {2005},
   address = {Gainesville},
   pages = {39-41},

}
以上编译成功，但如果将university换成school变成如下条目
@phdthesis{GoelA05,
   author = {Goel, Anukul},
   title = {Robust control of supercavitating vehicles in the presence of dynamic and uncertain cavity},
   school = {University of Florida},
   year = {2005},
   address = {Gainesville},
   pages = {39-41},

}
以上也能编译成功，说明university和school两个属性通用，但如果将address换成place published变成如下条目
@phdthesis{GoelA05,
   author = {Goel, Anukul},
   title = {Robust control of supercavitating vehicles in the presence of dynamic and uncertain cavity},
   university = {University of Florida},
   year = {2005},
   place published = {Gainesville},
   pages = {39-41},

}
以上编译失败，说明address是必选。并且参考模板中的reference.bib发现中文需要加language="zh"，说明language是可选。

所以想问，怎么查看gbt7714-numerical要求bib文件有哪些属性？同时奇怪的是，自动编译失败的，手动编译（xelatex+bibtex+xelatex+xelatex）却能成功。

**Comment by EagleLee0** [comment]
后来发现university和school两个属性虽然通用，但是university编译后不显示大学名，school才行

**Comment by syvshc** [comment]
阅读 texdoc gbt7714 http://mirrors.ctan.org/biblio/bibtex/contrib/gbt7714/gbt7714.pdf

**Comment by EagleLee0** [comment]
> 阅读 texdoc gbt7714 http://mirrors.ctan.org/biblio/bibtex/contrib/gbt7714/gbt7714.pdf

原来这是一个宏包啊也能texdoc，懂了！

读了gbt7714之后，发现可以自动识别语言，但又发现hithesis.pdf写道“需要额外增加一个Entry: language，将其设置为 zh 用来指示此参考文献为中文，以便 hithesis.bst 处理”，我又试了不加language属性编译效果是一样的，如图，那可以不加吗？如果不加会不会有什么不稳定？
![image](https://github.com/user-attachments/assets/d4592e01-c019-4571-bea7-fa818e1b88e9)

**Comment by syvshc** [comment]
`hithesis.bst` 和 `gbt7714-numerical.bst` 是两种格式, 用 `gbt7714-numerical` 的话看 `texdoc gbt7714` 即可

**Comment by EagleLee0** [comment]
> `hithesis.bst` 和 `gbt7714-numerical.bst` 是两种格式, 用 `gbt7714-numerical` 的话看 `texdoc gbt7714` 即可

明白明白，多谢大佬👍
