### ISSUE TITLE
二级标题/三级标题上下间距似乎和Word版本不同？

### ISSUE THREAD

**Issue by hzxie** [hithesis/hithesis#88]
**描述bug类型**

- 校区（哈尔滨/威海/深圳？）：哈尔滨

- 学位（本/硕/博？）：博

- 论文类型（毕业论文/开题/中期/博后/English Version？）：毕业论文

- 证据（与规范不符/与word模板不符？）：与word模板不符

- 证据所在网页（窝工规范或者word模板所在窝工官方网页）：http://hitgs.hit.edu.cn/ab/1f/c3425a109343/page.psp

**描述bug具体信息** 

窝工在（规范/word模板中）第（xxx）行规定格式为：

如图：

<img width="1280" alt="Word-Template" src="https://user-images.githubusercontent.com/1730504/111961760-6557b200-8b2c-11eb-812e-2b78af647a9f.png">

hithesis的格式为

如图：

<img width="1286" alt="LaTeX-Template" src="https://user-images.githubusercontent.com/1730504/111962031-c3849500-8b2c-11eb-9cc0-2d96ad3680c2.png">

**Comment by dustincys** [comment]
规范和word有歧义，还是按照自己喜欢的改间距吧

**Comment by hzxie** [comment]
@dustincys 
谢谢师兄（&好久不见）。
不过请问要怎么改？😂不会LaTeX😭

**Comment by dustincys** [comment]
在这里改一改
https://github.com/dustincys/hithesis/blob/master/hithesis.dtx#L5334

**Comment by hzxie** [comment]
好的 谢谢。

**Comment by hzxie** [comment]
但是我的目录下只有`hithesis.sty`和`hithesisbook.cls`，并没有`hithesis.dtx`。

**Comment by hzxie** [comment]
```
    section={
      afterindent=true,
      beforeskip={\ifhit@glue 13.5bp \@plus 1.677267bp \@minus 1.157391bp \else 13.5bp \fi},%上下空0.5行
      afterskip={\ifhit@glue 13.5bp \@plus 1.677267bp \@minus 1.157391bp  \else 13.5bp \fi},
      format={\hit@title@font\ifhit@glue\fontsize{15bp}{21bp \@plus 1.677267bp \@minus 1.157391bp}\else\fontsize{15bp}{21bp}\fi\selectfont\bfseries},
      aftername=\enspace,
      fixskip=true,
      break={},
    },
```

请问其中的`\ifhit@glue 13.5bp \@plus 1.677267bp \@minus 1.157391bp \else 13.5bp \fi`是什么意思？
特别是`13.5bp`、`1.677267bp`和`1.157391bp`分别是什么意思？
另外`@glue`，`\@plus`和` \@minus`又是什么意思？

**Comment by Poofee** [comment]
老师非要你改？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Haozhe Xie ***@***.***&gt;
发送时间: 2021年4月9日 13:57
收件人: dustincys/hithesis ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[dustincys/hithesis] 二级标题/三级标题上下间距似乎和Word版本不同？ (#88)





    section={      afterindent=true,      ***@***.*** 13.5bp ***@***.*** 1.677267bp ***@***.*** 1.157391bp \else 13.5bp \fi},%上下空0.5行      ***@***.*** 13.5bp ***@***.*** 1.677267bp ***@***.*** 1.157391bp  \else 13.5bp \fi},      ***@***.***@***@***.***\fontsize{15bp}{21bp ***@***.*** 1.677267bp ***@***.*** 1.157391bp}\else\fontsize{15bp}{21bp}\fi\selectfont\bfseries},      aftername=\enspace,      fixskip=true,      break={},    },
***@***.*** 13.5bp ***@***.*** 1.677267bp ***@***.*** 1.157391bp \else 13.5bp \fi是什么意思？
特别是13.5bp、1.677267bp和1.157391bp分别是什么意思？
***@***.******@***.***和 ***@***.***又是什么意思？

**Comment by hzxie** [comment]
@Poofee 
对啊，而且我没看懂你们说的歧义说的是啥。
所以我也不知道要怎么argue😭

**Comment by Poofee** [comment]
歧义就是没有规定固定标准，



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Haozhe Xie ***@***.***&gt;
发送时间: 2021年4月9日 14:23
收件人: dustincys/hithesis ***@***.***&gt;
抄送: Poofee ***@***.***&gt;, Mention ***@***.***&gt;
主题: 回复：[dustincys/hithesis] 二级标题/三级标题上下间距似乎和Word版本不同？ (#88)





 
@Poofee
 对啊，而且我没看懂你们说的歧义说的是啥。
 所以我也不知道要怎么argue😭

**Comment by hzxie** [comment]
@Poofee 
为啥有歧义？我没有看懂那个文档里的说明。
可以解释一下吗？我去和我的老板argue一波。

**Comment by hzxie** [comment]
另外，请问要怎么修改？
模板里提到的那些数值都什么意思？

**Comment by Poofee** [comment]
不要问我  我不懂 改不了

**Comment by dustincys** [comment]
> ```
>     section={
>       afterindent=true,
>       beforeskip={\ifhit@glue 13.5bp \@plus 1.677267bp \@minus 1.157391bp \else 13.5bp \fi},%上下空0.5行
>       afterskip={\ifhit@glue 13.5bp \@plus 1.677267bp \@minus 1.157391bp  \else 13.5bp \fi},
>       format={\hit@title@font\ifhit@glue\fontsize{15bp}{21bp \@plus 1.677267bp \@minus 1.157391bp}\else\fontsize{15bp}{21bp}\fi\selectfont\bfseries},
>       aftername=\enspace,
>       fixskip=true,
>       break={},
>     },
> ```
> 
> 请问其中的`\ifhit@glue 13.5bp \@plus 1.677267bp \@minus 1.157391bp \else 13.5bp \fi`是什么意思？
> 特别是`13.5bp`、`1.677267bp`和`1.157391bp`分别是什么意思？
> 另外`@glue`，`\@plus`和` \@minus`又是什么意思？

＠glue 是定义在hithesis包内的变量glue，控制是不是弹性行距用。plus minus 是长度变量的加减。
13.5bp就是是长度。这里根据个人喜好设置吧。

**Comment by hzxie** [comment]
哦，好的。
那请问1.677267bp和1.157391bp又是什么意思呢？
而且为什么要先加一个数再减一个数？直接加上一个数不行吗？
