### ISSUE TITLE
深圳校区硕士毕业论文更新了部分格式并添加了英文目录

### ISSUE THREAD

**Issue by venturi123** [hithesis/hithesis#97]
**描述bug类型**

- 校区（哈尔滨/威海/深圳？）：
深圳

- 学位（本/硕/博？）：
硕

- 论文类型（毕业论文/开题/中期/博后/English Version？）：
毕业论文

- 证据（与规范不符/与word模板不符？）：
与word模版不符

- 证据所在网页（窝工规范或者word模板所在窝工官方网页）：
http://due.hitsz.edu.cn/info/1211/1859.htm

**描述bug具体信息** 
　　2021版 `哈尔滨工业大学（深圳）全日制硕士研究生学位论文书写范例-理工类` 对标题、封面、章节名称、分图编号、参考文献方括号样式进行变动，并添加了英文目录。

　　具体变更可见附件2中 `1.1哈尔滨工业大学（深圳）硕士学位论文格式要求及审查要点2021年5月` 和 `1.2哈尔滨工业大学（深圳）全日制硕士研究生学位论文书写范例-理工类（2021版，修订处涂红）` 

如图：
![image](https://user-images.githubusercontent.com/19996167/120096446-2c584100-c15e-11eb-979d-8336bb0a199e.png)

![image](https://user-images.githubusercontent.com/19996167/120096458-3ed27a80-c15e-11eb-9346-2f0bc7f3676f.png)

![image](https://user-images.githubusercontent.com/19996167/120096464-4560f200-c15e-11eb-91a0-91c5e724c045.png)

![image](https://user-images.githubusercontent.com/19996167/120096466-498d0f80-c15e-11eb-8676-194bd02a46bb.png)

![image](https://user-images.githubusercontent.com/19996167/120096471-514cb400-c15e-11eb-80c3-06f8a74d4068.png)

![image](https://user-images.githubusercontent.com/19996167/120096475-56a9fe80-c15e-11eb-88bb-7d2eec938d64.png)

![image](https://user-images.githubusercontent.com/19996167/120096477-5c9fdf80-c15e-11eb-8663-fa5336146384.png)

![image](https://user-images.githubusercontent.com/19996167/120096481-60cbfd00-c15e-11eb-9d4f-4a51de60dcfe.png)

**Comment by dustincys** [comment]
深圳校区每年都要变动一次

**Comment by syvshc** [comment]
参考文献部分在 https://github.com/dustincys/hithesis/commit/057fcf6eb8368a0c59b3b95a29f970ba59c59c7f 中更新

**Comment by syvshc** [comment]
话说我在链接处下载的书写范例中没有看到英文目录啊：

![image](https://user-images.githubusercontent.com/38098591/171162767-1cc1469a-aff8-41d3-b1fe-78596d8bf6d2.png)

**Comment by zicaijun** [comment]
你好，请问一下深圳校区硕士毕业论文参考文献中的中文括号显示不出来，这个需要怎样操作呢？

**Comment by syvshc** [comment]
> 你好，请问一下深圳校区硕士毕业论文参考文献中的中文括号显示不出来，这个需要怎样操作呢？

请提一个新的 issue
